/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.Controller;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.InputEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author Janek
 */
public class ControllerSettings extends javax.swing.JFrame {

    private ControllerSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public ControllerSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void setTab(int index)
    {
        if(index==0 || index==1)
        {
            jTabbedPane1.setSelectedIndex(index);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        MainPanel1 = new javax.swing.JPanel();
        L2UnderText = new javax.swing.JLabel();
        L2Btn = new javax.swing.JButton();
        L1Btn = new javax.swing.JButton();
        L1UnderText = new javax.swing.JLabel();
        UpBtn = new javax.swing.JButton();
        UpUnderText = new javax.swing.JLabel();
        R2Btn = new javax.swing.JButton();
        R2UnderText = new javax.swing.JLabel();
        R1Btn = new javax.swing.JButton();
        R1UnderText = new javax.swing.JLabel();
        TriangleBtn = new javax.swing.JButton();
        TriangleUnderText = new javax.swing.JLabel();
        SelectBtn = new javax.swing.JButton();
        SelectUnderText = new javax.swing.JLabel();
        StartBtn = new javax.swing.JButton();
        StartUnderText = new javax.swing.JLabel();
        LeftBtn = new javax.swing.JButton();
        LeftUnderText = new javax.swing.JLabel();
        ResolutionText1 = new javax.swing.JLabel();
        ResolutionText = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        RightBtn = new javax.swing.JButton();
        RightUnderText = new javax.swing.JLabel();
        SquareBtn = new javax.swing.JButton();
        SquareUnderText = new javax.swing.JLabel();
        CircleBtn = new javax.swing.JButton();
        CircleUnderText = new javax.swing.JLabel();
        DownBtn = new javax.swing.JButton();
        DownUnderText = new javax.swing.JLabel();
        CrossBtn = new javax.swing.JButton();
        CrossUnderText = new javax.swing.JLabel();
        AnalogueBtn = new javax.swing.JButton();
        AnalogueUnderText = new javax.swing.JLabel();
        LXBtn = new javax.swing.JButton();
        LXUnderText = new javax.swing.JLabel();
        RXBtn = new javax.swing.JButton();
        RXUnderText = new javax.swing.JLabel();
        LYBtn = new javax.swing.JButton();
        LYUnderText = new javax.swing.JLabel();
        RYBtn = new javax.swing.JButton();
        RYUnderText = new javax.swing.JLabel();
        L3Btn = new javax.swing.JButton();
        L3UnderText = new javax.swing.JLabel();
        R3Btn = new javax.swing.JButton();
        R3UnderText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AlphaMultiPassText18 = new javax.swing.JLabel();
        AlphaMultiPassTick1 = new javax.swing.JCheckBox();
        AlphaMultiPassText19 = new javax.swing.JLabel();
        AlphaMultiPassTick2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        MainPanel2 = new javax.swing.JPanel();
        L2UnderText1 = new javax.swing.JLabel();
        L2Btn1 = new javax.swing.JButton();
        L1Btn1 = new javax.swing.JButton();
        L1UnderText1 = new javax.swing.JLabel();
        UpBtn1 = new javax.swing.JButton();
        UpUnderText1 = new javax.swing.JLabel();
        R2Btn1 = new javax.swing.JButton();
        R2UnderText1 = new javax.swing.JLabel();
        R1Btn1 = new javax.swing.JButton();
        R1UnderText1 = new javax.swing.JLabel();
        TriangleBtn1 = new javax.swing.JButton();
        TriangleUnderText1 = new javax.swing.JLabel();
        SelectBtn1 = new javax.swing.JButton();
        SelectUnderText1 = new javax.swing.JLabel();
        StartBtn1 = new javax.swing.JButton();
        StartUnderText1 = new javax.swing.JLabel();
        LeftBtn1 = new javax.swing.JButton();
        LeftUnderText1 = new javax.swing.JLabel();
        ResolutionText2 = new javax.swing.JLabel();
        ResolutionText3 = new javax.swing.JLabel();
        RightBtn1 = new javax.swing.JButton();
        RightUnderText1 = new javax.swing.JLabel();
        SquareBtn1 = new javax.swing.JButton();
        SquareUnderText1 = new javax.swing.JLabel();
        CircleBtn1 = new javax.swing.JButton();
        CircleUnderText1 = new javax.swing.JLabel();
        DownBtn1 = new javax.swing.JButton();
        DownUnderText1 = new javax.swing.JLabel();
        CrossBtn1 = new javax.swing.JButton();
        CrossUnderText1 = new javax.swing.JLabel();
        AnalogueBtn1 = new javax.swing.JButton();
        AnalogueUnderText1 = new javax.swing.JLabel();
        LXBtn1 = new javax.swing.JButton();
        LXUnderText1 = new javax.swing.JLabel();
        RXBtn1 = new javax.swing.JButton();
        RXUnderText1 = new javax.swing.JLabel();
        LYBtn1 = new javax.swing.JButton();
        LYUnderText1 = new javax.swing.JLabel();
        RYBtn1 = new javax.swing.JButton();
        RYUnderText1 = new javax.swing.JLabel();
        L3Btn1 = new javax.swing.JButton();
        L3UnderText1 = new javax.swing.JLabel();
        R3Btn1 = new javax.swing.JButton();
        R3UnderText1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AlphaMultiPassText20 = new javax.swing.JLabel();
        AlphaMultiPassTick3 = new javax.swing.JCheckBox();
        AlphaMultiPassText21 = new javax.swing.JLabel();
        AlphaMultiPassTick4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel1.setBackground(new java.awt.Color(204, 255, 255));
        MainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L2UnderText.setBackground(new java.awt.Color(204, 204, 255));
        L2UnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L2UnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2UnderText.setText("E");
        L2UnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L2UnderText.setOpaque(true);
        MainPanel1.add(L2UnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 90, 20));

        L2Btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L2Btn.setText("L2");
        L2Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2BtnActionPerformed(evt);
            }
        });
        MainPanel1.add(L2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, 20));

        L1Btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L1Btn.setText("L1");
        L1Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1BtnActionPerformed(evt);
            }
        });
        MainPanel1.add(L1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, 20));

        L1UnderText.setBackground(new java.awt.Color(204, 204, 255));
        L1UnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L1UnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L1UnderText.setText("W");
        L1UnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L1UnderText.setOpaque(true);
        MainPanel1.add(L1UnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 20));

        UpBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UpBtn.setText("Up");
        UpBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(UpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 20));

        UpUnderText.setBackground(new java.awt.Color(204, 204, 255));
        UpUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UpUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpUnderText.setText("Up Arrow");
        UpUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpUnderText.setOpaque(true);
        MainPanel1.add(UpUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, 20));

        R2Btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R2Btn.setText("R2");
        R2Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        R2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2BtnActionPerformed(evt);
            }
        });
        MainPanel1.add(R2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 90, 20));

        R2UnderText.setBackground(new java.awt.Color(204, 204, 255));
        R2UnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R2UnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R2UnderText.setText("T");
        R2UnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R2UnderText.setOpaque(true);
        MainPanel1.add(R2UnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 90, 20));

        R1Btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R1Btn.setText("R1");
        R1Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        R1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1BtnActionPerformed(evt);
            }
        });
        MainPanel1.add(R1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 90, 20));

        R1UnderText.setBackground(new java.awt.Color(204, 204, 255));
        R1UnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R1UnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R1UnderText.setText("R");
        R1UnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R1UnderText.setOpaque(true);
        MainPanel1.add(R1UnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 90, 20));

        TriangleBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TriangleBtn.setText("Triangle");
        TriangleBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TriangleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TriangleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangleBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(TriangleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 90, 20));

        TriangleUnderText.setBackground(new java.awt.Color(204, 204, 255));
        TriangleUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TriangleUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TriangleUnderText.setText("D");
        TriangleUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TriangleUnderText.setOpaque(true);
        MainPanel1.add(TriangleUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 90, 20));

        SelectBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SelectBtn.setText("Select");
        SelectBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SelectBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(SelectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, 20));

        SelectUnderText.setBackground(new java.awt.Color(204, 204, 255));
        SelectUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SelectUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectUnderText.setText("C");
        SelectUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SelectUnderText.setOpaque(true);
        MainPanel1.add(SelectUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, 20));

        StartBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StartBtn.setText("Start");
        StartBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(StartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 90, 20));

        StartUnderText.setBackground(new java.awt.Color(204, 204, 255));
        StartUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StartUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StartUnderText.setText("V");
        StartUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StartUnderText.setOpaque(true);
        MainPanel1.add(StartUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 90, 20));

        LeftBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LeftBtn.setText("Left");
        LeftBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LeftBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LeftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(LeftBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 20));

        LeftUnderText.setBackground(new java.awt.Color(204, 204, 255));
        LeftUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LeftUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LeftUnderText.setText("Left Arrow");
        LeftUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LeftUnderText.setOpaque(true);
        MainPanel1.add(LeftUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 20));

        ResolutionText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResolutionText1.setText("1. Click any box");
        MainPanel1.add(ResolutionText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 20));

        ResolutionText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResolutionText.setText("2. Press the button on your keyboard/controller that you wish to map it to");
        MainPanel1.add(ResolutionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 600, 20));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 70, 30));

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 630, 70, 30));

        RightBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RightBtn.setText("Right");
        RightBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RightBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(RightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, 20));

        RightUnderText.setBackground(new java.awt.Color(204, 204, 255));
        RightUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RightUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightUnderText.setText("Right Arrow");
        RightUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RightUnderText.setOpaque(true);
        MainPanel1.add(RightUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, 20));

        SquareBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SquareBtn.setText("Square");
        SquareBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SquareBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SquareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(SquareBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 90, 20));

        SquareUnderText.setBackground(new java.awt.Color(204, 204, 255));
        SquareUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SquareUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SquareUnderText.setText("S");
        SquareUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SquareUnderText.setOpaque(true);
        MainPanel1.add(SquareUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 90, 20));

        CircleBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CircleBtn.setText("Circle");
        CircleBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CircleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CircleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircleBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(CircleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 90, 20));

        CircleUnderText.setBackground(new java.awt.Color(204, 204, 255));
        CircleUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CircleUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CircleUnderText.setText("X");
        CircleUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CircleUnderText.setOpaque(true);
        MainPanel1.add(CircleUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 90, 20));

        DownBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DownBtn.setText("Down");
        DownBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DownBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(DownBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, 20));

        DownUnderText.setBackground(new java.awt.Color(204, 204, 255));
        DownUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DownUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DownUnderText.setText("Down Arrow");
        DownUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DownUnderText.setOpaque(true);
        MainPanel1.add(DownUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, 20));

        CrossBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CrossBtn.setText("Cross");
        CrossBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CrossBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrossBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrossBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(CrossBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 90, 20));

        CrossUnderText.setBackground(new java.awt.Color(204, 204, 255));
        CrossUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CrossUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrossUnderText.setText("Z");
        CrossUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CrossUnderText.setOpaque(true);
        MainPanel1.add(CrossUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 90, 20));

        AnalogueBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AnalogueBtn.setText("Analogue");
        AnalogueBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AnalogueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AnalogueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalogueBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(AnalogueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 90, 20));

        AnalogueUnderText.setBackground(new java.awt.Color(204, 204, 255));
        AnalogueUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AnalogueUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnalogueUnderText.setText("None");
        AnalogueUnderText.setToolTipText("");
        AnalogueUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AnalogueUnderText.setOpaque(true);
        MainPanel1.add(AnalogueUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 90, 20));

        LXBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LXBtn.setText("LX");
        LXBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LXBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LXBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LXBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(LXBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 90, 20));

        LXUnderText.setBackground(new java.awt.Color(204, 204, 255));
        LXUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LXUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LXUnderText.setText("None");
        LXUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LXUnderText.setOpaque(true);
        MainPanel1.add(LXUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, 20));

        RXBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RXBtn.setText("RX");
        RXBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RXBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RXBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RXBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(RXBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 90, 20));

        RXUnderText.setBackground(new java.awt.Color(204, 204, 255));
        RXUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RXUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RXUnderText.setText("None");
        RXUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RXUnderText.setOpaque(true);
        MainPanel1.add(RXUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 90, 20));

        LYBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LYBtn.setText("LY");
        LYBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LYBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LYBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LYBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(LYBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 90, 20));

        LYUnderText.setBackground(new java.awt.Color(204, 204, 255));
        LYUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LYUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LYUnderText.setText("None");
        LYUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LYUnderText.setOpaque(true);
        MainPanel1.add(LYUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 90, 20));

        RYBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RYBtn.setText("RY");
        RYBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RYBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RYBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RYBtnActionPerformed(evt);
            }
        });
        MainPanel1.add(RYBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 90, 20));

        RYUnderText.setBackground(new java.awt.Color(204, 204, 255));
        RYUnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RYUnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RYUnderText.setText("None");
        RYUnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RYUnderText.setOpaque(true);
        MainPanel1.add(RYUnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 90, 20));

        L3Btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L3Btn.setText("L3");
        L3Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3BtnActionPerformed(evt);
            }
        });
        MainPanel1.add(L3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 90, 20));

        L3UnderText.setBackground(new java.awt.Color(204, 204, 255));
        L3UnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L3UnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L3UnderText.setText("None");
        L3UnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L3UnderText.setOpaque(true);
        MainPanel1.add(L3UnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 90, 20));

        R3Btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R3Btn.setText("R3");
        R3Btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        R3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3BtnActionPerformed(evt);
            }
        });
        MainPanel1.add(R3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 90, 20));

        R3UnderText.setBackground(new java.awt.Color(204, 204, 255));
        R3UnderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R3UnderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R3UnderText.setText("None");
        R3UnderText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R3UnderText.setOpaque(true);
        MainPanel1.add(R3UnderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 90, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlphaMultiPassText18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText18.setText("ENABLE DUALSHOCK2");
        jPanel1.add(AlphaMultiPassText18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 20));

        AlphaMultiPassTick1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(AlphaMultiPassTick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        AlphaMultiPassText19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText19.setText("VISUAL VIBRATION");
        jPanel1.add(AlphaMultiPassText19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 20));

        AlphaMultiPassTick2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(AlphaMultiPassTick2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, -1));

        MainPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/Controller_Medium_2.png"))); // NOI18N
        MainPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jTabbedPane1.addTab("tab1", MainPanel1);

        MainPanel2.setBackground(new java.awt.Color(255, 204, 204));
        MainPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L2UnderText1.setBackground(new java.awt.Color(204, 204, 255));
        L2UnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L2UnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2UnderText1.setText("E");
        L2UnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L2UnderText1.setOpaque(true);
        MainPanel2.add(L2UnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 90, 20));

        L2Btn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L2Btn1.setText("L2");
        L2Btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L2Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L2Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Btn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(L2Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, 20));

        L1Btn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L1Btn1.setText("L1");
        L1Btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L1Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1Btn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(L1Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, 20));

        L1UnderText1.setBackground(new java.awt.Color(204, 204, 255));
        L1UnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L1UnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L1UnderText1.setText("W");
        L1UnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L1UnderText1.setOpaque(true);
        MainPanel2.add(L1UnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 20));

        UpBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UpBtn1.setText("Up");
        UpBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UpBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(UpBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 20));

        UpUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        UpUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UpUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpUnderText1.setText("Up Arrow");
        UpUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpUnderText1.setOpaque(true);
        MainPanel2.add(UpUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, 20));

        R2Btn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R2Btn1.setText("R2");
        R2Btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R2Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        R2Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2Btn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(R2Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 90, 20));

        R2UnderText1.setBackground(new java.awt.Color(204, 204, 255));
        R2UnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R2UnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R2UnderText1.setText("T");
        R2UnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R2UnderText1.setOpaque(true);
        MainPanel2.add(R2UnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 90, 20));

        R1Btn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R1Btn1.setText("R1");
        R1Btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R1Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        R1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1Btn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(R1Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 90, 20));

        R1UnderText1.setBackground(new java.awt.Color(204, 204, 255));
        R1UnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R1UnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R1UnderText1.setText("R");
        R1UnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R1UnderText1.setOpaque(true);
        MainPanel2.add(R1UnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 90, 20));

        TriangleBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TriangleBtn1.setText("Triangle");
        TriangleBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TriangleBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TriangleBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangleBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(TriangleBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 90, 20));

        TriangleUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        TriangleUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TriangleUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TriangleUnderText1.setText("D");
        TriangleUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TriangleUnderText1.setOpaque(true);
        MainPanel2.add(TriangleUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 90, 20));

        SelectBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SelectBtn1.setText("Select");
        SelectBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SelectBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SelectBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(SelectBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, 20));

        SelectUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        SelectUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SelectUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectUnderText1.setText("C");
        SelectUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SelectUnderText1.setOpaque(true);
        MainPanel2.add(SelectUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, 20));

        StartBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StartBtn1.setText("Start");
        StartBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StartBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StartBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(StartBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 90, 20));

        StartUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        StartUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StartUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StartUnderText1.setText("V");
        StartUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StartUnderText1.setOpaque(true);
        MainPanel2.add(StartUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 90, 20));

        LeftBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LeftBtn1.setText("Left");
        LeftBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LeftBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LeftBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(LeftBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 20));

        LeftUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        LeftUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LeftUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LeftUnderText1.setText("Left Arrow");
        LeftUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LeftUnderText1.setOpaque(true);
        MainPanel2.add(LeftUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 20));

        ResolutionText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResolutionText2.setText("1. Click any box");
        MainPanel2.add(ResolutionText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 20));

        ResolutionText3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResolutionText3.setText("2. Press the button on your keyboard/controller that you wish to map it to");
        MainPanel2.add(ResolutionText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 600, 20));

        RightBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RightBtn1.setText("Right");
        RightBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RightBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RightBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(RightBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, 20));

        RightUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        RightUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RightUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightUnderText1.setText("Right Arrow");
        RightUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RightUnderText1.setOpaque(true);
        MainPanel2.add(RightUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, 20));

        SquareBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SquareBtn1.setText("Square");
        SquareBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SquareBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SquareBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(SquareBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 90, 20));

        SquareUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        SquareUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SquareUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SquareUnderText1.setText("S");
        SquareUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SquareUnderText1.setOpaque(true);
        MainPanel2.add(SquareUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 90, 20));

        CircleBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CircleBtn1.setText("Circle");
        CircleBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CircleBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CircleBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircleBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(CircleBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 90, 20));

        CircleUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        CircleUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CircleUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CircleUnderText1.setText("X");
        CircleUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CircleUnderText1.setOpaque(true);
        MainPanel2.add(CircleUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 90, 20));

        DownBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DownBtn1.setText("Down");
        DownBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DownBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DownBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(DownBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, 20));

        DownUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        DownUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DownUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DownUnderText1.setText("Down Arrow");
        DownUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DownUnderText1.setOpaque(true);
        MainPanel2.add(DownUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, 20));

        CrossBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CrossBtn1.setText("Cross");
        CrossBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CrossBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrossBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrossBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(CrossBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 90, 20));

        CrossUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        CrossUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CrossUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrossUnderText1.setText("Z");
        CrossUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CrossUnderText1.setOpaque(true);
        MainPanel2.add(CrossUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 90, 20));

        AnalogueBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AnalogueBtn1.setText("Analogue");
        AnalogueBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AnalogueBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AnalogueBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalogueBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(AnalogueBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 90, 20));

        AnalogueUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        AnalogueUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AnalogueUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnalogueUnderText1.setText("None");
        AnalogueUnderText1.setToolTipText("");
        AnalogueUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AnalogueUnderText1.setOpaque(true);
        MainPanel2.add(AnalogueUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 90, 20));

        LXBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LXBtn1.setText("LX");
        LXBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LXBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LXBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LXBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(LXBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 90, 20));

        LXUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        LXUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LXUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LXUnderText1.setText("None");
        LXUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LXUnderText1.setOpaque(true);
        MainPanel2.add(LXUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, 20));

        RXBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RXBtn1.setText("RX");
        RXBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RXBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RXBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RXBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(RXBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 90, 20));

        RXUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        RXUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RXUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RXUnderText1.setText("None");
        RXUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RXUnderText1.setOpaque(true);
        MainPanel2.add(RXUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 90, 20));

        LYBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LYBtn1.setText("LY");
        LYBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LYBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LYBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LYBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(LYBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 90, 20));

        LYUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        LYUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LYUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LYUnderText1.setText("None");
        LYUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LYUnderText1.setOpaque(true);
        MainPanel2.add(LYUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 90, 20));

        RYBtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RYBtn1.setText("RY");
        RYBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RYBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RYBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RYBtn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(RYBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 90, 20));

        RYUnderText1.setBackground(new java.awt.Color(204, 204, 255));
        RYUnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RYUnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RYUnderText1.setText("None");
        RYUnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RYUnderText1.setOpaque(true);
        MainPanel2.add(RYUnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 90, 20));

        L3Btn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L3Btn1.setText("L3");
        L3Btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L3Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L3Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Btn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(L3Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 90, 20));

        L3UnderText1.setBackground(new java.awt.Color(204, 204, 255));
        L3UnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        L3UnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L3UnderText1.setText("None");
        L3UnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L3UnderText1.setOpaque(true);
        MainPanel2.add(L3UnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 90, 20));

        R3Btn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R3Btn1.setText("R3");
        R3Btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R3Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        R3Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3Btn1ActionPerformed(evt);
            }
        });
        MainPanel2.add(R3Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 90, 20));

        R3UnderText1.setBackground(new java.awt.Color(204, 204, 255));
        R3UnderText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        R3UnderText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R3UnderText1.setText("None");
        R3UnderText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        R3UnderText1.setOpaque(true);
        MainPanel2.add(R3UnderText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 90, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/Controller_Medium_2.png"))); // NOI18N
        MainPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlphaMultiPassText20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText20.setText("ENABLE DUALSHOCK2");
        jPanel2.add(AlphaMultiPassText20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 20));

        AlphaMultiPassTick3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(AlphaMultiPassTick3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        AlphaMultiPassText21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText21.setText("VISUAL VIBRATION");
        jPanel2.add(AlphaMultiPassText21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 20));

        AlphaMultiPassTick4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(AlphaMultiPassTick4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, -1));

        MainPanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 240, 40));

        jTabbedPane1.addTab("tab2", MainPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed

    }//GEN-LAST:event_SaveBtnActionPerformed
    
    private void DisableOrEnableButtons(boolean action)
    {
        java.awt.EventQueue.invokeLater(() -> {
            L2Btn.setEnabled(action);
            R2Btn.setEnabled(action);
            L1Btn.setEnabled(action);
            R1Btn.setEnabled(action);
            UpBtn.setEnabled(action);
            TriangleBtn.setEnabled(action);
            SelectBtn.setEnabled(action);
            StartBtn.setEnabled(action);
            LeftBtn.setEnabled(action);
            RightBtn.setEnabled(action);
            SquareBtn.setEnabled(action);
            CircleBtn.setEnabled(action);
            DownBtn.setEnabled(action);
            CrossBtn.setEnabled(action);
            AnalogueBtn.setEnabled(action);
            LXBtn.setEnabled(action);
            RXBtn.setEnabled(action);
            L3Btn.setEnabled(action);
            R3Btn.setEnabled(action);
        });
    }
    
     private void DisableOrEnableButtons1(boolean action)
    {
        java.awt.EventQueue.invokeLater(() -> {
            L2Btn1.setEnabled(action);
            R2Btn1.setEnabled(action);
            L1Btn1.setEnabled(action);
            R1Btn1.setEnabled(action);
            UpBtn1.setEnabled(action);
            TriangleBtn1.setEnabled(action);
            SelectBtn1.setEnabled(action);
            StartBtn1.setEnabled(action);
            LeftBtn1.setEnabled(action);
            RightBtn1.setEnabled(action);
            SquareBtn1.setEnabled(action);
            CircleBtn1.setEnabled(action);
            DownBtn1.setEnabled(action);
            CrossBtn1.setEnabled(action);
            AnalogueBtn1.setEnabled(action);
            LXBtn1.setEnabled(action);
            RXBtn1.setEnabled(action);
            L3Btn1.setEnabled(action);
            R3Btn1.setEnabled(action);
        });
    }
    
    private void changeUnderButtonText(int index, char c)
    {
        java.awt.EventQueue.invokeLater(() -> {
            switch(index)
            {
            case 0:
                L2UnderText.setText(String.valueOf(c));
                break;
            case 1:
                R2UnderText.setText(String.valueOf(c));
                break;
            case 2:
                L1UnderText.setText(String.valueOf(c));
                break;
            case 3:
                R1UnderText.setText(String.valueOf(c));
                break;
            case 4:
                UpUnderText.setText(String.valueOf(c));
                break;
            case 5:
                TriangleUnderText.setText(String.valueOf(c));
                break;
            case 6:
                SelectUnderText.setText(String.valueOf(c));
                break;
            case 7:
                StartUnderText.setText(String.valueOf(c));
                break;
            case 8:
                LeftUnderText.setText(String.valueOf(c));
                break; 
            case 9:
                RightUnderText.setText(String.valueOf(c));
                break; 
            case 10:
                SquareUnderText.setText(String.valueOf(c));
                break; 
            case 11:
                CircleUnderText.setText(String.valueOf(c));
                break;
            case 12:
                DownUnderText.setText(String.valueOf(c));
                break;
            case 13:
                CrossUnderText.setText(String.valueOf(c));
                break;
            case 14:
                AnalogueUnderText.setText(String.valueOf(c));
                break;
            case 15:
                LXUnderText.setText(String.valueOf(c));
                break;
            case 16:
                RXUnderText.setText(String.valueOf(c));
                break;
            case 17:
                LYUnderText.setText(String.valueOf(c));
                break;
            case 18:
                RYUnderText.setText(String.valueOf(c));
                break;
            case 19:
                L3UnderText.setText(String.valueOf(c));
                break;
            case 20:
                R3UnderText.setText(String.valueOf(c));
                break;
            default:
                break;
        }
        });
    }
    
    private void changeUnderButtonText1(int index, char c)
    {
        java.awt.EventQueue.invokeLater(() -> {
            switch(index)
            {
            case 30:
                L2UnderText1.setText(String.valueOf(c));
                break;
            case 31:
                R2UnderText1.setText(String.valueOf(c));
                break;
            case 32:
                L1UnderText1.setText(String.valueOf(c));
                break;
            case 33:
                R1UnderText1.setText(String.valueOf(c));
                break;
            case 34:
                UpUnderText1.setText(String.valueOf(c));
                break;
            case 35:
                TriangleUnderText1.setText(String.valueOf(c));
                break;
            case 36:
                SelectUnderText1.setText(String.valueOf(c));
                break;
            case 37:
                StartUnderText1.setText(String.valueOf(c));
                break;
            case 38:
                LeftUnderText1.setText(String.valueOf(c));
                break; 
            case 39:
                RightUnderText1.setText(String.valueOf(c));
                break; 
            case 40:
                SquareUnderText1.setText(String.valueOf(c));
                break; 
            case 41:
                CircleUnderText1.setText(String.valueOf(c));
                break;
            case 42:
                DownUnderText1.setText(String.valueOf(c));
                break;
            case 43:
                CrossUnderText1.setText(String.valueOf(c));
                break;
            case 44:
                AnalogueUnderText1.setText(String.valueOf(c));
                break;
            case 45:
                LXUnderText1.setText(String.valueOf(c));
                break;
            case 46:
                RXUnderText1.setText(String.valueOf(c));
                break;
            case 47:
                LYUnderText1.setText(String.valueOf(c));
                break;
            case 48:
                RYUnderText1.setText(String.valueOf(c));
                break;
            case 49:
                L3UnderText1.setText(String.valueOf(c));
                break;
            case 50:
                R3UnderText1.setText(String.valueOf(c));
                break;
            default:
                break;
        }
        });
    }
    
    private volatile UserInputHolder key = new UserInputHolder();
    private boolean added =false;
    private volatile Character last='_';
    private void getKeyPress(int skip)
    {
            DisableOrEnableButtons(false);
            DisableOrEnableButtons1(false);
            key.setBooleanValue(false);
            if(!added)
            {
                added =true;
            KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher((KeyEvent ke) -> {
               synchronized (key) {
                  switch (ke.getID()) {
                      case KeyEvent.KEY_PRESSED:
                          if(!key.getBooleanValue())
                              {
                              last = key.getCharacter();
                              key.setCharacter(ke.getKeyChar());
                              key.setBooleanValue(true);
                              key.notify();
                              }
                          break;
                  }
                  return false;
              }
          });
          }
            
          Thread t1 = new Thread(() ->
          {
              synchronized(key)
              {
                  if(!key.getBooleanValue())
                  {
                      try {
                          key.wait();
                      } catch (InterruptedException ex) {
                          Logger.getLogger(ControllerSettings.class.getName()).log(Level.SEVERE, null, ex);
                      }
                  }
                  key.setBooleanValue(false);
                  System.out.println(skip + " " + key.getCharacter());
                  if(skip<=20)
                  {
                      changeUnderButtonText(skip, key.getCharacter());
                  }
                  else
                  {
                      changeUnderButtonText1(skip, key.getCharacter());
                  }
                  DisableOrEnableButtons(true);
                  DisableOrEnableButtons1(true);
                  
              }
          });
          t1.start();
    }
    
    
    private void L2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2BtnActionPerformed
        getKeyPress(0);   
    }//GEN-LAST:event_L2BtnActionPerformed

    private void R2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2BtnActionPerformed
       getKeyPress(1);
    }//GEN-LAST:event_R2BtnActionPerformed

    private void L1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1BtnActionPerformed
        getKeyPress(2);
    }//GEN-LAST:event_L1BtnActionPerformed

    private void R1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1BtnActionPerformed
        getKeyPress(3);
    }//GEN-LAST:event_R1BtnActionPerformed

    private void UpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpBtnActionPerformed
        getKeyPress(4);
    }//GEN-LAST:event_UpBtnActionPerformed

    private void TriangleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangleBtnActionPerformed
        getKeyPress(5);
    }//GEN-LAST:event_TriangleBtnActionPerformed

    private void SelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBtnActionPerformed
        getKeyPress(6);
    }//GEN-LAST:event_SelectBtnActionPerformed

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        getKeyPress(7);
    }//GEN-LAST:event_StartBtnActionPerformed

    private void LeftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftBtnActionPerformed
        getKeyPress(8);
    }//GEN-LAST:event_LeftBtnActionPerformed

    private void RightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightBtnActionPerformed
        getKeyPress(9);
    }//GEN-LAST:event_RightBtnActionPerformed

    private void SquareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareBtnActionPerformed
        getKeyPress(10);
    }//GEN-LAST:event_SquareBtnActionPerformed

    private void CircleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleBtnActionPerformed
        getKeyPress(11);
    }//GEN-LAST:event_CircleBtnActionPerformed

    private void DownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownBtnActionPerformed
        getKeyPress(12);
    }//GEN-LAST:event_DownBtnActionPerformed

    private void CrossBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrossBtnActionPerformed
        getKeyPress(13);
    }//GEN-LAST:event_CrossBtnActionPerformed

    private void AnalogueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalogueBtnActionPerformed
        getKeyPress(14);
    }//GEN-LAST:event_AnalogueBtnActionPerformed

    private void LXBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LXBtnActionPerformed
        getKeyPress(15);
    }//GEN-LAST:event_LXBtnActionPerformed

    private void RXBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RXBtnActionPerformed
        getKeyPress(16);
    }//GEN-LAST:event_RXBtnActionPerformed

    private void LYBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LYBtnActionPerformed
        getKeyPress(17);
    }//GEN-LAST:event_LYBtnActionPerformed

    private void RYBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RYBtnActionPerformed
        getKeyPress(18);
    }//GEN-LAST:event_RYBtnActionPerformed

    private void L3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3BtnActionPerformed
        getKeyPress(19);
    }//GEN-LAST:event_L3BtnActionPerformed

    private void R3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3BtnActionPerformed
        getKeyPress(20);
    }//GEN-LAST:event_R3BtnActionPerformed

    
    
    
    private void L2Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Btn1ActionPerformed
        getKeyPress(30);
    }//GEN-LAST:event_L2Btn1ActionPerformed

    private void L1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1Btn1ActionPerformed
        getKeyPress(32);
    }//GEN-LAST:event_L1Btn1ActionPerformed

    private void UpBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpBtn1ActionPerformed
        getKeyPress(34);
    }//GEN-LAST:event_UpBtn1ActionPerformed

    private void R2Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2Btn1ActionPerformed
        getKeyPress(31);
    }//GEN-LAST:event_R2Btn1ActionPerformed

    private void R1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1Btn1ActionPerformed
        getKeyPress(33);
    }//GEN-LAST:event_R1Btn1ActionPerformed

    private void TriangleBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangleBtn1ActionPerformed
        getKeyPress(35);
    }//GEN-LAST:event_TriangleBtn1ActionPerformed

    private void SelectBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBtn1ActionPerformed
        getKeyPress(36);
    }//GEN-LAST:event_SelectBtn1ActionPerformed

    private void StartBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtn1ActionPerformed
        getKeyPress(37);
    }//GEN-LAST:event_StartBtn1ActionPerformed

    private void LeftBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftBtn1ActionPerformed
        getKeyPress(38);
    }//GEN-LAST:event_LeftBtn1ActionPerformed

    private void RightBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightBtn1ActionPerformed
        getKeyPress(39);
    }//GEN-LAST:event_RightBtn1ActionPerformed

    private void SquareBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareBtn1ActionPerformed
        getKeyPress(40);
    }//GEN-LAST:event_SquareBtn1ActionPerformed

    private void CircleBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleBtn1ActionPerformed
        getKeyPress(41);
    }//GEN-LAST:event_CircleBtn1ActionPerformed

    private void DownBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownBtn1ActionPerformed
        getKeyPress(42);
    }//GEN-LAST:event_DownBtn1ActionPerformed

    private void CrossBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrossBtn1ActionPerformed
        getKeyPress(43);
    }//GEN-LAST:event_CrossBtn1ActionPerformed

    private void AnalogueBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalogueBtn1ActionPerformed
        getKeyPress(44);
    }//GEN-LAST:event_AnalogueBtn1ActionPerformed

    private void LXBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LXBtn1ActionPerformed
        getKeyPress(45);
    }//GEN-LAST:event_LXBtn1ActionPerformed

    private void RXBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RXBtn1ActionPerformed
        getKeyPress(46);
    }//GEN-LAST:event_RXBtn1ActionPerformed

    private void LYBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LYBtn1ActionPerformed
        getKeyPress(47);
    }//GEN-LAST:event_LYBtn1ActionPerformed

    private void RYBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RYBtn1ActionPerformed
        getKeyPress(48);
    }//GEN-LAST:event_RYBtn1ActionPerformed

    private void L3Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Btn1ActionPerformed
        getKeyPress(49);
    }//GEN-LAST:event_L3Btn1ActionPerformed

    private void R3Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3Btn1ActionPerformed
        getKeyPress(50);
    }//GEN-LAST:event_R3Btn1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlphaMultiPassText18;
    private javax.swing.JLabel AlphaMultiPassText19;
    private javax.swing.JLabel AlphaMultiPassText20;
    private javax.swing.JLabel AlphaMultiPassText21;
    private javax.swing.JCheckBox AlphaMultiPassTick1;
    private javax.swing.JCheckBox AlphaMultiPassTick2;
    private javax.swing.JCheckBox AlphaMultiPassTick3;
    private javax.swing.JCheckBox AlphaMultiPassTick4;
    private javax.swing.JButton AnalogueBtn;
    private javax.swing.JButton AnalogueBtn1;
    private javax.swing.JLabel AnalogueUnderText;
    private javax.swing.JLabel AnalogueUnderText1;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CircleBtn;
    private javax.swing.JButton CircleBtn1;
    private javax.swing.JLabel CircleUnderText;
    private javax.swing.JLabel CircleUnderText1;
    private javax.swing.JButton CrossBtn;
    private javax.swing.JButton CrossBtn1;
    private javax.swing.JLabel CrossUnderText;
    private javax.swing.JLabel CrossUnderText1;
    private javax.swing.JButton DownBtn;
    private javax.swing.JButton DownBtn1;
    private javax.swing.JLabel DownUnderText;
    private javax.swing.JLabel DownUnderText1;
    private javax.swing.JButton L1Btn;
    private javax.swing.JButton L1Btn1;
    private javax.swing.JLabel L1UnderText;
    private javax.swing.JLabel L1UnderText1;
    private javax.swing.JButton L2Btn;
    private javax.swing.JButton L2Btn1;
    private javax.swing.JLabel L2UnderText;
    private javax.swing.JLabel L2UnderText1;
    private javax.swing.JButton L3Btn;
    private javax.swing.JButton L3Btn1;
    private javax.swing.JLabel L3UnderText;
    private javax.swing.JLabel L3UnderText1;
    private javax.swing.JButton LXBtn;
    private javax.swing.JButton LXBtn1;
    private javax.swing.JLabel LXUnderText;
    private javax.swing.JLabel LXUnderText1;
    private javax.swing.JButton LYBtn;
    private javax.swing.JButton LYBtn1;
    private javax.swing.JLabel LYUnderText;
    private javax.swing.JLabel LYUnderText1;
    private javax.swing.JButton LeftBtn;
    private javax.swing.JButton LeftBtn1;
    private javax.swing.JLabel LeftUnderText;
    private javax.swing.JLabel LeftUnderText1;
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JPanel MainPanel2;
    private javax.swing.JButton R1Btn;
    private javax.swing.JButton R1Btn1;
    private javax.swing.JLabel R1UnderText;
    private javax.swing.JLabel R1UnderText1;
    private javax.swing.JButton R2Btn;
    private javax.swing.JButton R2Btn1;
    private javax.swing.JLabel R2UnderText;
    private javax.swing.JLabel R2UnderText1;
    private javax.swing.JButton R3Btn;
    private javax.swing.JButton R3Btn1;
    private javax.swing.JLabel R3UnderText;
    private javax.swing.JLabel R3UnderText1;
    private javax.swing.JButton RXBtn;
    private javax.swing.JButton RXBtn1;
    private javax.swing.JLabel RXUnderText;
    private javax.swing.JLabel RXUnderText1;
    private javax.swing.JButton RYBtn;
    private javax.swing.JButton RYBtn1;
    private javax.swing.JLabel RYUnderText;
    private javax.swing.JLabel RYUnderText1;
    private javax.swing.JLabel ResolutionText;
    private javax.swing.JLabel ResolutionText1;
    private javax.swing.JLabel ResolutionText2;
    private javax.swing.JLabel ResolutionText3;
    private javax.swing.JButton RightBtn;
    private javax.swing.JButton RightBtn1;
    private javax.swing.JLabel RightUnderText;
    private javax.swing.JLabel RightUnderText1;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SelectBtn;
    private javax.swing.JButton SelectBtn1;
    private javax.swing.JLabel SelectUnderText;
    private javax.swing.JLabel SelectUnderText1;
    private javax.swing.JButton SquareBtn;
    private javax.swing.JButton SquareBtn1;
    private javax.swing.JLabel SquareUnderText;
    private javax.swing.JLabel SquareUnderText1;
    private javax.swing.JButton StartBtn;
    private javax.swing.JButton StartBtn1;
    private javax.swing.JLabel StartUnderText;
    private javax.swing.JLabel StartUnderText1;
    private javax.swing.JButton TriangleBtn;
    private javax.swing.JButton TriangleBtn1;
    private javax.swing.JLabel TriangleUnderText;
    private javax.swing.JLabel TriangleUnderText1;
    private javax.swing.JButton UpBtn;
    private javax.swing.JButton UpBtn1;
    private javax.swing.JLabel UpUnderText;
    private javax.swing.JLabel UpUnderText1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
