/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.BG_COLOR;

import hci_assignment.MainMenu;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class ColorSettings extends javax.swing.JFrame {

    private ColorSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public ColorSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SaveBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        GraphicsText8 = new javax.swing.JLabel();
        ColorPicker = new javax.swing.JColorChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn1.setText("Save");
        SaveBtn1.setToolTipText("Save your choice");
        SaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setToolTipText("Go back the the previous screen");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        GraphicsText8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GraphicsText8.setText("Select Background Color");
        MainPanel.add(GraphicsText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 20));
        MainPanel.add(ColorPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtn1ActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            java.awt.Color color = ColorPicker.getColor();
            BACKGROUND_COLOR.setColor(color);
            ((MainMenu)previousWindow).setColorAgain();
            MainPanel.setBackground(BACKGROUND_COLOR.color);
        });
    }//GEN-LAST:event_SaveBtn1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JColorChooser ColorPicker;
    private javax.swing.JLabel GraphicsText8;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SaveBtn1;
    // End of variables declaration//GEN-END:variables
}
