/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.Graphics;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class AdvancedGraphicsSettings extends javax.swing.JFrame {

    private AdvancedGraphicsSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public AdvancedGraphicsSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ColorDepthText = new javax.swing.JLabel();
        TextureQualText = new javax.swing.JLabel();
        TextureFilteringText = new javax.swing.JLabel();
        HighResTexturesText = new javax.swing.JLabel();
        FPSLimitText = new javax.swing.JLabel();
        ColorDepthBox = new javax.swing.JComboBox<>();
        TextureQualityBox = new javax.swing.JComboBox<>();
        TextureFilteringBox = new javax.swing.JComboBox<>();
        HighResTexturesBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ShowFPSText = new javax.swing.JLabel();
        FrameSkippingText = new javax.swing.JLabel();
        SaveBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        CompatibilitySettingsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ShowFPSTick = new javax.swing.JCheckBox();
        FrameSkippingTick = new javax.swing.JCheckBox();
        FPSLimitTick = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColorDepthText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ColorDepthText.setText("Color Depth");
        ColorDepthText.setToolTipText("");
        MainPanel.add(ColorDepthText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 40));

        TextureQualText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextureQualText.setText("Texture Quality");
        MainPanel.add(TextureQualText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, 40));

        TextureFilteringText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextureFilteringText.setText("Texture filtering");
        MainPanel.add(TextureFilteringText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, 40));

        HighResTexturesText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HighResTexturesText.setText("High res textures");
        MainPanel.add(HighResTexturesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, 40));

        FPSLimitText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FPSLimitText.setText("FPS Limit");
        MainPanel.add(FPSLimitText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 80, 40));

        ColorDepthBox.setBackground(new java.awt.Color(204, 204, 204));
        ColorDepthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32", "16" }));
        ColorDepthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorDepthBoxActionPerformed(evt);
            }
        });
        MainPanel.add(ColorDepthBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 240, -1));

        TextureQualityBox.setBackground(new java.awt.Color(204, 204, 204));
        TextureQualityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver default", "Fastest", "Fast", "Best" }));
        TextureQualityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextureQualityBoxActionPerformed(evt);
            }
        });
        MainPanel.add(TextureQualityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 240, -1));

        TextureFilteringBox.setBackground(new java.awt.Color(204, 204, 204));
        TextureFilteringBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Standard - Glitches", "Extended - No black borders", "Standard - unfiltered 2D", "Extended - unfiltered 2D", "Standard - Smoothed Sptites", "Extended - Smoothed Sprites" }));
        TextureFilteringBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextureFilteringBoxActionPerformed(evt);
            }
        });
        MainPanel.add(TextureFilteringBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 240, -1));

        HighResTexturesBox.setBackground(new java.awt.Color(204, 204, 204));
        HighResTexturesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "2X Sampling", "Stretched" }));
        HighResTexturesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighResTexturesBoxActionPerformed(evt);
            }
        });
        MainPanel.add(HighResTexturesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 240, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/Graphics_advanced_bg_1.png"))); // NOI18N
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        ShowFPSText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ShowFPSText.setText("Show FPS");
        MainPanel.add(ShowFPSText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 80, 40));

        FrameSkippingText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FrameSkippingText.setText("Frame Skipping");
        MainPanel.add(FrameSkippingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 130, 40));

        SaveBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn1.setText("Save");
        SaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        CompatibilitySettingsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CompatibilitySettingsBtn.setText("Compatibility Settings");
        CompatibilitySettingsBtn.setToolTipText("hacks to fix for some games");
        CompatibilitySettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompatibilitySettingsBtnActionPerformed(evt);
            }
        });
        MainPanel.add(CompatibilitySettingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/Graphics_advanced_bg_2.png"))); // NOI18N
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        MainPanel.add(ShowFPSTick, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));
        MainPanel.add(FrameSkippingTick, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));
        MainPanel.add(FPSLimitTick, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HighResTexturesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighResTexturesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HighResTexturesBoxActionPerformed
    
    //First box
    private void ColorDepthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorDepthBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorDepthBoxActionPerformed

    private void TextureQualityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextureQualityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextureQualityBoxActionPerformed

    private void TextureFilteringBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextureFilteringBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextureFilteringBoxActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtn1ActionPerformed

    private void CompatibilitySettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompatibilitySettingsBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            GraphicsCompatibilitySettings gcs = new GraphicsCompatibilitySettings(thisClass);
            thisClass.setVisible(false);
            gcs.setVisible(true);
        });
    }//GEN-LAST:event_CompatibilitySettingsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox<String> ColorDepthBox;
    private javax.swing.JLabel ColorDepthText;
    private javax.swing.JButton CompatibilitySettingsBtn;
    private javax.swing.JLabel FPSLimitText;
    private javax.swing.JCheckBox FPSLimitTick;
    private javax.swing.JLabel FrameSkippingText;
    private javax.swing.JCheckBox FrameSkippingTick;
    private javax.swing.JComboBox<String> HighResTexturesBox;
    private javax.swing.JLabel HighResTexturesText;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SaveBtn1;
    private javax.swing.JLabel ShowFPSText;
    private javax.swing.JCheckBox ShowFPSTick;
    private javax.swing.JComboBox<String> TextureFilteringBox;
    private javax.swing.JLabel TextureFilteringText;
    private javax.swing.JLabel TextureQualText;
    private javax.swing.JComboBox<String> TextureQualityBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
