/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.Graphics;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import hci_assignment.Sounds.AdvancedSoundSettings;
import java.awt.Image;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class GraphicsSettings extends javax.swing.JFrame {

    private GraphicsSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public GraphicsSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ResolutionText = new javax.swing.JLabel();
        DisplayModeText = new javax.swing.JLabel();
        VSyncText = new javax.swing.JLabel();
        AspectRatioText = new javax.swing.JLabel();
        DisplayModeBox = new javax.swing.JComboBox<>();
        VSyncBox = new javax.swing.JComboBox<>();
        AspectRatioBox = new javax.swing.JComboBox<>();
        SaveBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        AdvancedSettingsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VertResolution = new javax.swing.JTextField();
        XText = new javax.swing.JLabel();
        HorizResolution = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResolutionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ResolutionText.setText("Resolution");
        ResolutionText.setToolTipText("PixelsX x PixelsY");
        MainPanel.add(ResolutionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 90, 40));

        DisplayModeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DisplayModeText.setText("Display Mode");
        DisplayModeText.setToolTipText("Windowed is when there are borders");
        MainPanel.add(DisplayModeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, 40));

        VSyncText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VSyncText.setText("V-sync");
        VSyncText.setToolTipText("The game's framerate will not exceed your monitor's refrash rate");
        MainPanel.add(VSyncText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 40));

        AspectRatioText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AspectRatioText.setText("Aspect ratio");
        AspectRatioText.setToolTipText("16:9 modern, 4:3 old");
        MainPanel.add(AspectRatioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, 40));

        DisplayModeBox.setBackground(new java.awt.Color(204, 204, 204));
        DisplayModeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fullscreen", "Windowed" }));
        DisplayModeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayModeBoxActionPerformed(evt);
            }
        });
        MainPanel.add(DisplayModeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 240, -1));

        VSyncBox.setBackground(new java.awt.Color(204, 204, 204));
        VSyncBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On", "Off" }));
        VSyncBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VSyncBoxActionPerformed(evt);
            }
        });
        MainPanel.add(VSyncBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 240, -1));

        AspectRatioBox.setBackground(new java.awt.Color(204, 204, 204));
        AspectRatioBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4:3", "16:9", "16:10" }));
        AspectRatioBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AspectRatioBoxActionPerformed(evt);
            }
        });
        MainPanel.add(AspectRatioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 240, -1));

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        AdvancedSettingsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdvancedSettingsBtn.setText("Advanced Settings");
        AdvancedSettingsBtn.setToolTipText("For more advanced users");
        AdvancedSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancedSettingsBtnActionPerformed(evt);
            }
        });
        MainPanel.add(AdvancedSettingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/Graphics_bg1Small.png"))); // NOI18N
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        VertResolution.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VertResolution.setText("1080");
        MainPanel.add(VertResolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, -1));

        XText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        XText.setText("X");
        MainPanel.add(XText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 10, 40));

        HorizResolution.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HorizResolution.setText("1920");
        MainPanel.add(HorizResolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AspectRatioBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AspectRatioBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AspectRatioBoxActionPerformed
    
    private void DisplayModeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayModeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayModeBoxActionPerformed

    private void VSyncBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VSyncBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VSyncBoxActionPerformed

    private void AdvancedSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancedSettingsBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            //construct object
            AdvancedGraphicsSettings ags = new AdvancedGraphicsSettings(thisClass);
            //hide this one
            thisClass.setVisible(false);
            //show the advanced settings
            ags.setVisible(true);
        });
    }//GEN-LAST:event_AdvancedSettingsBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed

    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdvancedSettingsBtn;
    private javax.swing.JComboBox<String> AspectRatioBox;
    private javax.swing.JLabel AspectRatioText;
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox<String> DisplayModeBox;
    private javax.swing.JLabel DisplayModeText;
    private javax.swing.JTextField HorizResolution;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel ResolutionText;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JComboBox<String> VSyncBox;
    private javax.swing.JLabel VSyncText;
    private javax.swing.JTextField VertResolution;
    private javax.swing.JLabel XText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
