/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.Graphics;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class SpecialGameFixes extends javax.swing.JFrame {

    private SpecialGameFixes thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public SpecialGameFixes(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        AlphaMultiPassText1 = new javax.swing.JLabel();
        AlphaMultiPassText2 = new javax.swing.JLabel();
        AlphaMultiPassText3 = new javax.swing.JLabel();
        AlphaMultiPassText4 = new javax.swing.JLabel();
        AlphaMultiPassText5 = new javax.swing.JLabel();
        AlphaMultiPassText6 = new javax.swing.JLabel();
        AlphaMultiPassText7 = new javax.swing.JLabel();
        AlphaMultiPassText8 = new javax.swing.JLabel();
        AlphaMultiPassText9 = new javax.swing.JLabel();
        AlphaMultiPassText10 = new javax.swing.JLabel();
        AlphaMultiPassText11 = new javax.swing.JLabel();
        AlphaMultiPassText12 = new javax.swing.JLabel();
        AlphaMultiPassText13 = new javax.swing.JLabel();
        AlphaMultiPassText14 = new javax.swing.JLabel();
        AlphaMultiPassText15 = new javax.swing.JLabel();
        AlphaMultiPassText16 = new javax.swing.JLabel();
        AlphaMultiPassText17 = new javax.swing.JLabel();
        AlphaMultiPassText = new javax.swing.JLabel();
        AlphaMultiPassText18 = new javax.swing.JLabel();
        AlphaMultiPassTick1 = new javax.swing.JCheckBox();
        AlphaMultiPassTick2 = new javax.swing.JCheckBox();
        AlphaMultiPassTick3 = new javax.swing.JCheckBox();
        AlphaMultiPassTick4 = new javax.swing.JCheckBox();
        AlphaMultiPassTick5 = new javax.swing.JCheckBox();
        AlphaMultiPassTick6 = new javax.swing.JCheckBox();
        AlphaMultiPassTick7 = new javax.swing.JCheckBox();
        AlphaMultiPassTick8 = new javax.swing.JCheckBox();
        AlphaMultiPassTick9 = new javax.swing.JCheckBox();
        AlphaMultiPassTick10 = new javax.swing.JCheckBox();
        AlphaMultiPassTick11 = new javax.swing.JCheckBox();
        AlphaMultiPassTick12 = new javax.swing.JCheckBox();
        AlphaMultiPassTick13 = new javax.swing.JCheckBox();
        AlphaMultiPassTick14 = new javax.swing.JCheckBox();
        AlphaMultiPassTick15 = new javax.swing.JCheckBox();
        AlphaMultiPassTick16 = new javax.swing.JCheckBox();
        AlphaMultiPassTick17 = new javax.swing.JCheckBox();
        AlphaMultiPassTick = new javax.swing.JCheckBox();
        AlphaMultiPassText19 = new javax.swing.JLabel();
        AlphaMultiPassText20 = new javax.swing.JLabel();
        AlphaMultiPassText21 = new javax.swing.JLabel();
        AlphaMultiPassText22 = new javax.swing.JLabel();
        AlphaMultiPassText23 = new javax.swing.JLabel();
        AlphaMultiPassText24 = new javax.swing.JLabel();
        AlphaMultiPassText25 = new javax.swing.JLabel();
        AlphaMultiPassText26 = new javax.swing.JLabel();
        AlphaMultiPassText27 = new javax.swing.JLabel();
        AlphaMultiPassText28 = new javax.swing.JLabel();
        AlphaMultiPassText29 = new javax.swing.JLabel();
        AlphaMultiPassText30 = new javax.swing.JLabel();
        AlphaMultiPassText31 = new javax.swing.JLabel();
        AlphaMultiPassText32 = new javax.swing.JLabel();
        AlphaMultiPassText33 = new javax.swing.JLabel();
        AlphaMultiPassText34 = new javax.swing.JLabel();
        AlphaMultiPassText35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        AlphaMultiPassText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText1.setText("Toggles busy flas after drawing");
        MainPanel.add(AlphaMultiPassText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 230, 20));

        AlphaMultiPassText2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText2.setText("0x00002: Direct framebuffer updates");
        MainPanel.add(AlphaMultiPassText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 20));

        AlphaMultiPassText3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText3.setText("0x00004: Ignore black brightness");
        MainPanel.add(AlphaMultiPassText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 20));

        AlphaMultiPassText4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText4.setText("0x00008: Swap front/back detection");
        MainPanel.add(AlphaMultiPassText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        AlphaMultiPassText5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText5.setText("0x00010: Disable coord check");
        MainPanel.add(AlphaMultiPassText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 20));

        AlphaMultiPassText6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText6.setText("0x00020: Remove blue glitches");
        MainPanel.add(AlphaMultiPassText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 20));

        AlphaMultiPassText7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText7.setText("0x00040: Mixed software FB access");
        MainPanel.add(AlphaMultiPassText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, 20));

        AlphaMultiPassText8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText8.setText("0x00080: Use PC fps calculation");
        MainPanel.add(AlphaMultiPassText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 20));

        AlphaMultiPassText9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText9.setText("0x00100: Use old frame skipping");
        MainPanel.add(AlphaMultiPassText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 20));

        AlphaMultiPassText10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText10.setText("0x00200: G4 polygon cache");
        MainPanel.add(AlphaMultiPassText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 20));

        AlphaMultiPassText11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText11.setText("0x00400: Fake subtractive blending");
        MainPanel.add(AlphaMultiPassText11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 20));

        AlphaMultiPassText12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText12.setText("0x00800: Lazy upload detection");
        MainPanel.add(AlphaMultiPassText12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, 20));

        AlphaMultiPassText13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText13.setText("0x01000: Odd/Even bit hack");
        MainPanel.add(AlphaMultiPassText13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, 20));

        AlphaMultiPassText14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText14.setText("0x02000: Expand screen width");
        MainPanel.add(AlphaMultiPassText14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 20));

        AlphaMultiPassText15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText15.setText("0x04000: Use old texturefiltering");
        MainPanel.add(AlphaMultiPassText15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, 20));

        AlphaMultiPassText16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText16.setText("0x08000: Special upload detection");
        MainPanel.add(AlphaMultiPassText16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, 20));

        AlphaMultiPassText17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText17.setText("0x10000: Use low-res fps timer");
        MainPanel.add(AlphaMultiPassText17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, 20));

        AlphaMultiPassText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText.setText("0x20000: Fake 'gpu busy' states");
        MainPanel.add(AlphaMultiPassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, 20));

        AlphaMultiPassText18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText18.setText("0x00001: Adjust framebuffer access");
        MainPanel.add(AlphaMultiPassText18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 200, 20));
        MainPanel.add(AlphaMultiPassTick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, -1));
        MainPanel.add(AlphaMultiPassTick2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 240, -1));
        MainPanel.add(AlphaMultiPassTick3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 240, -1));
        MainPanel.add(AlphaMultiPassTick4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, -1));
        MainPanel.add(AlphaMultiPassTick5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 240, -1));
        MainPanel.add(AlphaMultiPassTick6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 240, -1));
        MainPanel.add(AlphaMultiPassTick7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 240, -1));
        MainPanel.add(AlphaMultiPassTick8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, -1));
        MainPanel.add(AlphaMultiPassTick9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 240, -1));
        MainPanel.add(AlphaMultiPassTick10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 240, -1));
        MainPanel.add(AlphaMultiPassTick11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 240, -1));
        MainPanel.add(AlphaMultiPassTick12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 240, -1));
        MainPanel.add(AlphaMultiPassTick13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 240, -1));
        MainPanel.add(AlphaMultiPassTick14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 240, -1));
        MainPanel.add(AlphaMultiPassTick15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 240, -1));
        MainPanel.add(AlphaMultiPassTick16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 240, -1));
        MainPanel.add(AlphaMultiPassTick17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 240, -1));
        MainPanel.add(AlphaMultiPassTick, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 250, -1));

        AlphaMultiPassText19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText19.setText("ONLY for FF7 battle cursor/battle swirl");
        MainPanel.add(AlphaMultiPassText19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 240, 20));

        AlphaMultiPassText20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText20.setText("Speed up in nasty frame upload situations");
        MainPanel.add(AlphaMultiPassText20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 230, 20));

        AlphaMultiPassText21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText21.setText("Fixes black screens in Lunar");
        MainPanel.add(AlphaMultiPassText21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 230, 20));

        AlphaMultiPassText22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText22.setText("Speed freaks, Killer loop");
        MainPanel.add(AlphaMultiPassText22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 230, 20));

        AlphaMultiPassText23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText23.setText("Old coord compatibility mode");
        MainPanel.add(AlphaMultiPassText23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 230, 20));

        AlphaMultiPassText24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText24.setText("Leg. o. Dragoon, Alpha Multipass needed");
        MainPanel.add(AlphaMultiPassText24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 230, 20));

        AlphaMultiPassText25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText25.setText("Faster FB access on some systems/ATI");
        MainPanel.add(AlphaMultiPassText25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 230, 20));

        AlphaMultiPassText26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText26.setText("Better FPS limitation with some games");
        MainPanel.add(AlphaMultiPassText26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 230, 20));

        AlphaMultiPassText27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText27.setText("Skips only every second frame");
        MainPanel.add(AlphaMultiPassText27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 230, 20));

        AlphaMultiPassText28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText28.setText("ONLY for FF9 battle mode.. yellow rect");
        MainPanel.add(AlphaMultiPassText28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 230, 20));

        AlphaMultiPassText29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText29.setText("Needed by some buggy OpenGL ICD's");
        MainPanel.add(AlphaMultiPassText29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 230, 20));

        AlphaMultiPassText30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText30.setText("DW7 fix (not 100% perfect)");
        MainPanel.add(AlphaMultiPassText30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 230, 20));

        AlphaMultiPassText31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText31.setText("Needed with epsxe 1.5.2 and older");
        MainPanel.add(AlphaMultiPassText31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 230, 20));

        AlphaMultiPassText32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText32.setText("Shows the full arena in Capcom 2D fighers");
        MainPanel.add(AlphaMultiPassText32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 240, 20));

        AlphaMultiPassText33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText33.setText("Fixes black ares with some cards");
        MainPanel.add(AlphaMultiPassText33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 230, 20));

        AlphaMultiPassText34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText34.setText("May show some additional splash screens");
        MainPanel.add(AlphaMultiPassText34, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 230, 20));

        AlphaMultiPassText35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AlphaMultiPassText35.setText("For buggy motherboard chipsets");
        MainPanel.add(AlphaMultiPassText35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 230, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlphaMultiPassText;
    private javax.swing.JLabel AlphaMultiPassText1;
    private javax.swing.JLabel AlphaMultiPassText10;
    private javax.swing.JLabel AlphaMultiPassText11;
    private javax.swing.JLabel AlphaMultiPassText12;
    private javax.swing.JLabel AlphaMultiPassText13;
    private javax.swing.JLabel AlphaMultiPassText14;
    private javax.swing.JLabel AlphaMultiPassText15;
    private javax.swing.JLabel AlphaMultiPassText16;
    private javax.swing.JLabel AlphaMultiPassText17;
    private javax.swing.JLabel AlphaMultiPassText18;
    private javax.swing.JLabel AlphaMultiPassText19;
    private javax.swing.JLabel AlphaMultiPassText2;
    private javax.swing.JLabel AlphaMultiPassText20;
    private javax.swing.JLabel AlphaMultiPassText21;
    private javax.swing.JLabel AlphaMultiPassText22;
    private javax.swing.JLabel AlphaMultiPassText23;
    private javax.swing.JLabel AlphaMultiPassText24;
    private javax.swing.JLabel AlphaMultiPassText25;
    private javax.swing.JLabel AlphaMultiPassText26;
    private javax.swing.JLabel AlphaMultiPassText27;
    private javax.swing.JLabel AlphaMultiPassText28;
    private javax.swing.JLabel AlphaMultiPassText29;
    private javax.swing.JLabel AlphaMultiPassText3;
    private javax.swing.JLabel AlphaMultiPassText30;
    private javax.swing.JLabel AlphaMultiPassText31;
    private javax.swing.JLabel AlphaMultiPassText32;
    private javax.swing.JLabel AlphaMultiPassText33;
    private javax.swing.JLabel AlphaMultiPassText34;
    private javax.swing.JLabel AlphaMultiPassText35;
    private javax.swing.JLabel AlphaMultiPassText4;
    private javax.swing.JLabel AlphaMultiPassText5;
    private javax.swing.JLabel AlphaMultiPassText6;
    private javax.swing.JLabel AlphaMultiPassText7;
    private javax.swing.JLabel AlphaMultiPassText8;
    private javax.swing.JLabel AlphaMultiPassText9;
    private javax.swing.JCheckBox AlphaMultiPassTick;
    private javax.swing.JCheckBox AlphaMultiPassTick1;
    private javax.swing.JCheckBox AlphaMultiPassTick10;
    private javax.swing.JCheckBox AlphaMultiPassTick11;
    private javax.swing.JCheckBox AlphaMultiPassTick12;
    private javax.swing.JCheckBox AlphaMultiPassTick13;
    private javax.swing.JCheckBox AlphaMultiPassTick14;
    private javax.swing.JCheckBox AlphaMultiPassTick15;
    private javax.swing.JCheckBox AlphaMultiPassTick16;
    private javax.swing.JCheckBox AlphaMultiPassTick17;
    private javax.swing.JCheckBox AlphaMultiPassTick2;
    private javax.swing.JCheckBox AlphaMultiPassTick3;
    private javax.swing.JCheckBox AlphaMultiPassTick4;
    private javax.swing.JCheckBox AlphaMultiPassTick5;
    private javax.swing.JCheckBox AlphaMultiPassTick6;
    private javax.swing.JCheckBox AlphaMultiPassTick7;
    private javax.swing.JCheckBox AlphaMultiPassTick8;
    private javax.swing.JCheckBox AlphaMultiPassTick9;
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SaveBtn;
    // End of variables declaration//GEN-END:variables
}
