/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.MemoryCards;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import hci_assignment.PluginAndBIOS.GetUserDirectory;
import hci_assignment.PluginAndBIOS.PopUpMenu;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class MemoryCardsSettings extends javax.swing.JFrame {

    private MemoryCardsSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public MemoryCardsSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SaveBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        GraphicsText8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        GraphicsText9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        SelectMemCard1 = new javax.swing.JButton();
        FormatMemCard1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        SelectMemCard2 = new javax.swing.JButton();
        FormatMemCard2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn1.setText("Save");
        SaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, -1, -1));

        GraphicsText8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GraphicsText8.setText("Memory Card 1");
        MainPanel.add(GraphicsText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Save01", "Free", "3231", "Return of the Gore Splatt Monster pt2"},
                {"Save02", "Free", "3231", "Return of the Gore Splatt Monster pt2"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Status", "Game ID", "Game"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 480, 240));

        GraphicsText9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GraphicsText9.setText("Memory Card 2");
        MainPanel.add(GraphicsText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 130, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Save01", "Free", "3231", "Return of the Gore Splatt Monster pt2"},
                {"Save02", "Free", "3231", "Return of the Gore Splatt Monster pt2"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Status", "Game ID", "Game"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        MainPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 480, 240));

        jButton1.setText("Delete ->");
        jButton1.setToolTipText("Delete selected on right");
        MainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 80, -1));

        jButton2.setText("Copy ->");
        jButton2.setToolTipText("Copy selected from right");
        MainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 80, -1));

        jButton3.setText("<- Copy");
        jButton3.setToolTipText("Copy selected from left");
        MainPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 80, -1));

        jButton4.setText("Paste");
        MainPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 80, -1));

        jButton5.setText("<- Delete");
        jButton5.setToolTipText("Delete selected on left");
        MainPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 80, -1));

        jButton6.setText("Reload Memory Card");
        MainPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        SelectMemCard1.setText("Select Memory Card");
        SelectMemCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMemCard1ActionPerformed(evt);
            }
        });
        MainPanel.add(SelectMemCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        FormatMemCard1.setText("Format Memory Card");
        FormatMemCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatMemCard1ActionPerformed(evt);
            }
        });
        MainPanel.add(FormatMemCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField1.setText("memcards\\Mcd002.mcr");
        MainPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 480, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField2.setText("memcards\\Mcd001.mcr");
        MainPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 480, 30));

        SelectMemCard2.setText("Select Memory Card");
        SelectMemCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMemCard2ActionPerformed(evt);
            }
        });
        MainPanel.add(SelectMemCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        FormatMemCard2.setText("Format Memory Card");
        FormatMemCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatMemCard2ActionPerformed(evt);
            }
        });
        MainPanel.add(FormatMemCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        jButton11.setText("Reload Memory Card");
        MainPanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtn1ActionPerformed

    private void SelectMemCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMemCard1ActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GetUserDirectory(thisClass).setVisible(true);
        });
    }//GEN-LAST:event_SelectMemCard1ActionPerformed

    private void FormatMemCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormatMemCard1ActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            PopUpMenu pum = new PopUpMenu(thisClass);
            pum.setMessage("Are you sure you wish to format memory card 1?");
            pum.setVisible(true);
        });
    }//GEN-LAST:event_FormatMemCard1ActionPerformed

    private void SelectMemCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMemCard2ActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GetUserDirectory(thisClass).setVisible(true);
        });
    }//GEN-LAST:event_SelectMemCard2ActionPerformed

    private void FormatMemCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormatMemCard2ActionPerformed
         java.awt.EventQueue.invokeLater(() -> {
            PopUpMenu pum = new PopUpMenu(thisClass);
            pum.setMessage("Are you sure you wish to format memory card 2?");
            pum.setVisible(true);
        });
    }//GEN-LAST:event_FormatMemCard2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton FormatMemCard1;
    private javax.swing.JButton FormatMemCard2;
    private javax.swing.JLabel GraphicsText8;
    private javax.swing.JLabel GraphicsText9;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SaveBtn1;
    private javax.swing.JButton SelectMemCard1;
    private javax.swing.JButton SelectMemCard2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
