/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.PluginAndBIOS;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import hci_assignment.Controller.ControllerSettings;
import hci_assignment.Graphics.*;
import hci_assignment.Sounds.SoundSettings;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class PluginAndBIOS extends javax.swing.JFrame {

    private PluginAndBIOS thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public PluginAndBIOS(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        GraphicsText = new javax.swing.JLabel();
        GraphicsBox = new javax.swing.JComboBox<>();
        GraphicsConfigureBtn = new javax.swing.JButton();
        GraphicsTestButton = new javax.swing.JButton();
        GraphicsAboutBtn = new javax.swing.JButton();
        SoundText = new javax.swing.JLabel();
        SoundBox = new javax.swing.JComboBox<>();
        SoundConfigureBtn = new javax.swing.JButton();
        SoundTestBtn = new javax.swing.JButton();
        SoundAboutBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        FirstControllerText = new javax.swing.JLabel();
        FirstControllerBox = new javax.swing.JComboBox<>();
        FirstControllerConfigureBtn = new javax.swing.JButton();
        FirstControllerTestBtn = new javax.swing.JButton();
        FirstControllerAboutBtn = new javax.swing.JButton();
        SecondControllerText = new javax.swing.JLabel();
        SecondControllerBox = new javax.swing.JComboBox<>();
        SecondControllerConfigureBtn = new javax.swing.JButton();
        SecondControllerTestBtn = new javax.swing.JButton();
        SecondControllerAboutBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        CDROMText = new javax.swing.JLabel();
        CDROMBox = new javax.swing.JComboBox<>();
        CDROMConfigureBtn = new javax.swing.JButton();
        CDROMTestBtn = new javax.swing.JButton();
        CDROMAboutBtn = new javax.swing.JButton();
        BIOSText = new javax.swing.JLabel();
        BIOSBox = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        SetPluginsDirBtn = new javax.swing.JButton();
        SetBIOSDirBtn = new javax.swing.JButton();
        SystemTypeText = new javax.swing.JLabel();
        SystemTypeBox = new javax.swing.JComboBox<>();
        GraphicsText1 = new javax.swing.JLabel();
        GraphicsBox1 = new javax.swing.JComboBox<>();
        GraphicsConfigureBtn1 = new javax.swing.JButton();
        GraphicsTestButton1 = new javax.swing.JButton();
        GraphicsAboutBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, -1, -1));

        GraphicsText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText.setText("Graphics");
        MainPanel.add(GraphicsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 20));

        GraphicsBox.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Driver 1.17", "OpenGL Driver 1.78", "P.E.Op.S Software Driver 1.18" }));
        GraphicsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBoxActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 260, -1));

        GraphicsConfigureBtn.setText("Configure...");
        GraphicsConfigureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsConfigureBtnActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsConfigureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        GraphicsTestButton.setText("Test");
        GraphicsTestButton.setEnabled(false);
        GraphicsTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsTestButtonActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsTestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        GraphicsAboutBtn.setText("About");
        GraphicsAboutBtn.setEnabled(false);
        GraphicsAboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsAboutBtnActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsAboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        SoundText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SoundText.setText("Sound");
        MainPanel.add(SoundText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 60, 20));

        SoundBox.setBackground(new java.awt.Color(204, 204, 204));
        SoundBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DirectSound Driver 1.0", "P.E.Op.S DSound Audio Driver 1.9" }));
        SoundBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundBoxActionPerformed(evt);
            }
        });
        MainPanel.add(SoundBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 260, -1));

        SoundConfigureBtn.setText("Configure...");
        SoundConfigureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundConfigureBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SoundConfigureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        SoundTestBtn.setText("Test");
        SoundTestBtn.setEnabled(false);
        SoundTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundTestBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SoundTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        SoundAboutBtn.setText("About");
        SoundAboutBtn.setEnabled(false);
        SoundAboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundAboutBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SoundAboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));
        MainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 810, 10));

        FirstControllerText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstControllerText.setText("First Controller");
        MainPanel.add(FirstControllerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        FirstControllerBox.setBackground(new java.awt.Color(204, 204, 204));
        FirstControllerBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSSPSX PAD PLUGIN PRESSURE MOD 1.6" }));
        FirstControllerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstControllerBoxActionPerformed(evt);
            }
        });
        MainPanel.add(FirstControllerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 260, -1));

        FirstControllerConfigureBtn.setText("Configure...");
        FirstControllerConfigureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstControllerConfigureBtnActionPerformed(evt);
            }
        });
        MainPanel.add(FirstControllerConfigureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        FirstControllerTestBtn.setText("Test");
        FirstControllerTestBtn.setEnabled(false);
        FirstControllerTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstControllerTestBtnActionPerformed(evt);
            }
        });
        MainPanel.add(FirstControllerTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        FirstControllerAboutBtn.setText("About");
        FirstControllerAboutBtn.setEnabled(false);
        FirstControllerAboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstControllerAboutBtnActionPerformed(evt);
            }
        });
        MainPanel.add(FirstControllerAboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        SecondControllerText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SecondControllerText.setText("Second Controller");
        MainPanel.add(SecondControllerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 110, 20));

        SecondControllerBox.setBackground(new java.awt.Color(204, 204, 204));
        SecondControllerBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSSPSX PAD PLUGIN PRESSURE MOD 1.6" }));
        SecondControllerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondControllerBoxActionPerformed(evt);
            }
        });
        MainPanel.add(SecondControllerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 260, -1));

        SecondControllerConfigureBtn.setText("Configure...");
        SecondControllerConfigureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondControllerConfigureBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SecondControllerConfigureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        SecondControllerTestBtn.setText("Test");
        SecondControllerTestBtn.setEnabled(false);
        SecondControllerTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondControllerTestBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SecondControllerTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        SecondControllerAboutBtn.setText("About");
        SecondControllerAboutBtn.setEnabled(false);
        SecondControllerAboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondControllerAboutBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SecondControllerAboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));
        MainPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 810, 10));

        CDROMText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CDROMText.setText("CD-ROM");
        MainPanel.add(CDROMText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 20));

        CDROMBox.setBackground(new java.awt.Color(204, 204, 204));
        CDROMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SaPu's CD-ROM Plugin 1.3" }));
        CDROMBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDROMBoxActionPerformed(evt);
            }
        });
        MainPanel.add(CDROMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 270, -1));

        CDROMConfigureBtn.setText("Configure...");
        CDROMConfigureBtn.setEnabled(false);
        CDROMConfigureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDROMConfigureBtnActionPerformed(evt);
            }
        });
        MainPanel.add(CDROMConfigureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        CDROMTestBtn.setText("Test");
        CDROMTestBtn.setEnabled(false);
        CDROMTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDROMTestBtnActionPerformed(evt);
            }
        });
        MainPanel.add(CDROMTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        CDROMAboutBtn.setText("About");
        CDROMAboutBtn.setEnabled(false);
        CDROMAboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDROMAboutBtnActionPerformed(evt);
            }
        });
        MainPanel.add(CDROMAboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        BIOSText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BIOSText.setText("BIOS");
        MainPanel.add(BIOSText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 20));

        BIOSBox.setBackground(new java.awt.Color(204, 204, 204));
        BIOSBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simulate psx BIOS" }));
        BIOSBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIOSBoxActionPerformed(evt);
            }
        });
        MainPanel.add(BIOSBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 260, -1));
        MainPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 810, 10));

        SetPluginsDirBtn.setText("Set Plugins Directory...");
        SetPluginsDirBtn.setToolTipText("The directory your plugins are in");
        SetPluginsDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPluginsDirBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SetPluginsDirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        SetBIOSDirBtn.setText("Set BIOS Directory...");
        SetBIOSDirBtn.setToolTipText("The directory of the PS1 BIOS");
        SetBIOSDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetBIOSDirBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SetBIOSDirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        SystemTypeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SystemTypeText.setText("System Type");
        MainPanel.add(SystemTypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 90, 20));

        SystemTypeBox.setBackground(new java.awt.Color(204, 204, 204));
        SystemTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NTSC", "PAL" }));
        SystemTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemTypeBoxActionPerformed(evt);
            }
        });
        MainPanel.add(SystemTypeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 260, -1));

        GraphicsText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText1.setText("NetPlay");
        MainPanel.add(GraphicsText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 60, 20));

        GraphicsBox1.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disabled", "NetSock Driver 0.2" }));
        GraphicsBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBox1ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 260, -1));

        GraphicsConfigureBtn1.setText("Configure...");
        GraphicsConfigureBtn1.setEnabled(false);
        GraphicsConfigureBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsConfigureBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsConfigureBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        GraphicsTestButton1.setText("Test");
        GraphicsTestButton1.setEnabled(false);
        GraphicsTestButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsTestButton1ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsTestButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        GraphicsAboutBtn1.setText("About");
        GraphicsAboutBtn1.setEnabled(false);
        GraphicsAboutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsAboutBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsAboutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void GraphicsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBoxActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed

    }//GEN-LAST:event_SaveBtnActionPerformed

    private void GraphicsAboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsAboutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsAboutBtnActionPerformed

    private void GraphicsConfigureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsConfigureBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            thisClass.setVisible(false);
            new GraphicsSettings(thisClass).setVisible(true);
        });
    }//GEN-LAST:event_GraphicsConfigureBtnActionPerformed

    private void GraphicsTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsTestButtonActionPerformed

    private void SoundBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoundBoxActionPerformed

    private void SoundConfigureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundConfigureBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            thisClass.setVisible(false);
            new SoundSettings(thisClass).setVisible(true);
        });
    }//GEN-LAST:event_SoundConfigureBtnActionPerformed

    private void SoundTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundTestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoundTestBtnActionPerformed

    private void SoundAboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundAboutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoundAboutBtnActionPerformed

    private void FirstControllerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstControllerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstControllerBoxActionPerformed

    private void FirstControllerConfigureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstControllerConfigureBtnActionPerformed
       java.awt.EventQueue.invokeLater(() -> {
            thisClass.setVisible(false);
            new ControllerSettings(thisClass).setVisible(true);
        });
    }//GEN-LAST:event_FirstControllerConfigureBtnActionPerformed

    private void FirstControllerTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstControllerTestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstControllerTestBtnActionPerformed

    private void FirstControllerAboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstControllerAboutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstControllerAboutBtnActionPerformed

    private void SecondControllerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondControllerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondControllerBoxActionPerformed

    private void SecondControllerConfigureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondControllerConfigureBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            thisClass.setVisible(false);
            ControllerSettings cs = new ControllerSettings(thisClass);
            cs.setVisible(true);
            cs.setTab(1);
        });
    }//GEN-LAST:event_SecondControllerConfigureBtnActionPerformed

    private void SecondControllerTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondControllerTestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondControllerTestBtnActionPerformed

    private void SecondControllerAboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondControllerAboutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondControllerAboutBtnActionPerformed

    private void CDROMBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDROMBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDROMBoxActionPerformed

    private void CDROMConfigureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDROMConfigureBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDROMConfigureBtnActionPerformed

    private void CDROMTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDROMTestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDROMTestBtnActionPerformed

    private void CDROMAboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDROMAboutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDROMAboutBtnActionPerformed

    private void BIOSBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIOSBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIOSBoxActionPerformed

    private void SetPluginsDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPluginsDirBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            thisClass.setVisible(false);
            new GetUserDirectory(thisClass).setVisible(true);
        });
    }//GEN-LAST:event_SetPluginsDirBtnActionPerformed

    private void SetBIOSDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetBIOSDirBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            thisClass.setVisible(false);
            new GetUserDirectory(thisClass).setVisible(true);
        });
    }//GEN-LAST:event_SetBIOSDirBtnActionPerformed

    private void SystemTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemTypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SystemTypeBoxActionPerformed

    private void GraphicsBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBox1ActionPerformed

    private void GraphicsConfigureBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsConfigureBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsConfigureBtn1ActionPerformed

    private void GraphicsTestButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsTestButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsTestButton1ActionPerformed

    private void GraphicsAboutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsAboutBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsAboutBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BIOSBox;
    private javax.swing.JLabel BIOSText;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CDROMAboutBtn;
    private javax.swing.JComboBox<String> CDROMBox;
    private javax.swing.JButton CDROMConfigureBtn;
    private javax.swing.JButton CDROMTestBtn;
    private javax.swing.JLabel CDROMText;
    private javax.swing.JButton FirstControllerAboutBtn;
    private javax.swing.JComboBox<String> FirstControllerBox;
    private javax.swing.JButton FirstControllerConfigureBtn;
    private javax.swing.JButton FirstControllerTestBtn;
    private javax.swing.JLabel FirstControllerText;
    private javax.swing.JButton GraphicsAboutBtn;
    private javax.swing.JButton GraphicsAboutBtn1;
    private javax.swing.JComboBox<String> GraphicsBox;
    private javax.swing.JComboBox<String> GraphicsBox1;
    private javax.swing.JButton GraphicsConfigureBtn;
    private javax.swing.JButton GraphicsConfigureBtn1;
    private javax.swing.JButton GraphicsTestButton;
    private javax.swing.JButton GraphicsTestButton1;
    private javax.swing.JLabel GraphicsText;
    private javax.swing.JLabel GraphicsText1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SecondControllerAboutBtn;
    private javax.swing.JComboBox<String> SecondControllerBox;
    private javax.swing.JButton SecondControllerConfigureBtn;
    private javax.swing.JButton SecondControllerTestBtn;
    private javax.swing.JLabel SecondControllerText;
    private javax.swing.JButton SetBIOSDirBtn;
    private javax.swing.JButton SetPluginsDirBtn;
    private javax.swing.JButton SoundAboutBtn;
    private javax.swing.JComboBox<String> SoundBox;
    private javax.swing.JButton SoundConfigureBtn;
    private javax.swing.JButton SoundTestBtn;
    private javax.swing.JLabel SoundText;
    private javax.swing.JComboBox<String> SystemTypeBox;
    private javax.swing.JLabel SystemTypeText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
