/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.LanguageSettings;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import hci_assignment.MainMenu;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class LanguageSettings extends javax.swing.JFrame {

    private LanguageSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public LanguageSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        EnglishText = new javax.swing.JLabel();
        NotEnglishText = new javax.swing.JLabel();
        ItalianText = new javax.swing.JLabel();
        ChineseText = new javax.swing.JLabel();
        ChineseTradText1 = new javax.swing.JLabel();
        ChineseTradText2 = new javax.swing.JLabel();
        RussianText = new javax.swing.JLabel();
        PortugueseText = new javax.swing.JLabel();
        EnglishButton = new javax.swing.JToggleButton();
        NotEnglishButton = new javax.swing.JToggleButton();
        ItalianButton = new javax.swing.JToggleButton();
        ChineseButton = new javax.swing.JToggleButton();
        ChineseTradButton = new javax.swing.JToggleButton();
        RussianButton = new javax.swing.JToggleButton();
        PortugueseButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        EnglishText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EnglishText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EnglishText.setText("English");
        MainPanel.add(EnglishText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 30));

        NotEnglishText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NotEnglishText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NotEnglishText.setText("Not English");
        MainPanel.add(NotEnglishText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, 30));

        ItalianText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ItalianText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ItalianText.setText("Italian");
        MainPanel.add(ItalianText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 90, 40));

        ChineseText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChineseText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChineseText.setText("Chinese");
        MainPanel.add(ChineseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 90, 40));

        ChineseTradText1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChineseTradText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChineseTradText1.setText("Chinese");
        MainPanel.add(ChineseTradText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 90, -1));

        ChineseTradText2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChineseTradText2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChineseTradText2.setText("Traditional");
        MainPanel.add(ChineseTradText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 90, -1));

        RussianText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RussianText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RussianText.setText("Russian");
        MainPanel.add(RussianText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 90, -1));

        PortugueseText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PortugueseText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PortugueseText.setText("Portuguese");
        MainPanel.add(PortugueseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 90, -1));

        EnglishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/flags/English.png"))); // NOI18N
        EnglishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishButtonActionPerformed(evt);
            }
        });
        MainPanel.add(EnglishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, -1));

        NotEnglishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/flags/NotEnglish.png"))); // NOI18N
        NotEnglishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotEnglishButtonActionPerformed(evt);
            }
        });
        MainPanel.add(NotEnglishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 120, -1));

        ItalianButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/flags/Italian.png"))); // NOI18N
        ItalianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalianButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ItalianButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 120, -1));

        ChineseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/flags/Chinese.png"))); // NOI18N
        ChineseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChineseButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ChineseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 120, -1));

        ChineseTradButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/flags/ChineseTraditional.png"))); // NOI18N
        ChineseTradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChineseTradButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ChineseTradButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 120, -1));

        RussianButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/flags/Russian.png"))); // NOI18N
        RussianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RussianButtonActionPerformed(evt);
            }
        });
        MainPanel.add(RussianButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, -1));

        PortugueseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/flags/Portuguese.png"))); // NOI18N
        PortugueseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortugueseButtonActionPerformed(evt);
            }
        });
        MainPanel.add(PortugueseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/LanguageSelection_bg.png"))); // NOI18N
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
    java.awt.EventQueue.invokeLater(() -> {
            ((MainMenu)previousWindow).setLanguageFlag(selectedFlag);
        });
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void EnglishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            ChineseButton.setSelected(false);
            ChineseTradButton.setSelected(false);
            ItalianButton.setSelected(false);
            NotEnglishButton.setSelected(false);
            PortugueseButton.setSelected(false);
            RussianButton.setSelected(false);
            selectedFlag = 0;
        });
    }//GEN-LAST:event_EnglishButtonActionPerformed

    private void NotEnglishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotEnglishButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            ChineseButton.setSelected(false);
            ChineseTradButton.setSelected(false);
            ItalianButton.setSelected(false);
            EnglishButton.setSelected(false);
            PortugueseButton.setSelected(false);
            RussianButton.setSelected(false);
            selectedFlag = 1;
        });
    }//GEN-LAST:event_NotEnglishButtonActionPerformed

    private void ItalianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalianButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            ChineseButton.setSelected(false);
            ChineseTradButton.setSelected(false);
            NotEnglishButton.setSelected(false);
            EnglishButton.setSelected(false);
            PortugueseButton.setSelected(false);
            RussianButton.setSelected(false);
            selectedFlag = 2;
        });
    }//GEN-LAST:event_ItalianButtonActionPerformed

    private void ChineseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChineseButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            ItalianButton.setSelected(false);
            ChineseTradButton.setSelected(false);
            NotEnglishButton.setSelected(false);
            EnglishButton.setSelected(false);
            PortugueseButton.setSelected(false);
            RussianButton.setSelected(false);
            selectedFlag = 3;
        });
    }//GEN-LAST:event_ChineseButtonActionPerformed

    private void ChineseTradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChineseTradButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            ItalianButton.setSelected(false);
            ChineseButton.setSelected(false);
            NotEnglishButton.setSelected(false);
            EnglishButton.setSelected(false);
            PortugueseButton.setSelected(false);
            RussianButton.setSelected(false);
            selectedFlag = 4;
        });
    }//GEN-LAST:event_ChineseTradButtonActionPerformed

    private void RussianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RussianButtonActionPerformed
         java.awt.EventQueue.invokeLater(() -> {
            ItalianButton.setSelected(false);
            ChineseButton.setSelected(false);
            NotEnglishButton.setSelected(false);
            EnglishButton.setSelected(false);
            PortugueseButton.setSelected(false);
            ChineseTradButton.setSelected(false);
            selectedFlag = 5;
        });
    }//GEN-LAST:event_RussianButtonActionPerformed

    private void PortugueseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortugueseButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            ItalianButton.setSelected(false);
            ChineseButton.setSelected(false);
            NotEnglishButton.setSelected(false);
            EnglishButton.setSelected(false);
            RussianButton.setSelected(false);
            ChineseTradButton.setSelected(false);
            selectedFlag = 6;
        });
    }//GEN-LAST:event_PortugueseButtonActionPerformed
    
    //Keep track of which flag has been selected
    private int selectedFlag = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JToggleButton ChineseButton;
    private javax.swing.JLabel ChineseText;
    private javax.swing.JToggleButton ChineseTradButton;
    private javax.swing.JLabel ChineseTradText1;
    private javax.swing.JLabel ChineseTradText2;
    private javax.swing.JToggleButton EnglishButton;
    private javax.swing.JLabel EnglishText;
    private javax.swing.JToggleButton ItalianButton;
    private javax.swing.JLabel ItalianText;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JToggleButton NotEnglishButton;
    private javax.swing.JLabel NotEnglishText;
    private javax.swing.JToggleButton PortugueseButton;
    private javax.swing.JLabel PortugueseText;
    private javax.swing.JToggleButton RussianButton;
    private javax.swing.JLabel RussianText;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
