/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.CPU;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class CPUSettings extends javax.swing.JFrame {

    private CPUSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public CPUSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SaveBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        AlphaMultiPassText18 = new javax.swing.JLabel();
        AlphaMultiPassTick1 = new javax.swing.JCheckBox();
        AlphaMultiPassText19 = new javax.swing.JLabel();
        AlphaMultiPassTick2 = new javax.swing.JCheckBox();
        AlphaMultiPassText20 = new javax.swing.JLabel();
        AlphaMultiPassTick3 = new javax.swing.JCheckBox();
        AlphaMultiPassText21 = new javax.swing.JLabel();
        AlphaMultiPassTick4 = new javax.swing.JCheckBox();
        AlphaMultiPassText22 = new javax.swing.JLabel();
        AlphaMultiPassTick5 = new javax.swing.JCheckBox();
        AlphaMultiPassText23 = new javax.swing.JLabel();
        AlphaMultiPassTick6 = new javax.swing.JCheckBox();
        AlphaMultiPassText24 = new javax.swing.JLabel();
        AlphaMultiPassTick7 = new javax.swing.JCheckBox();
        AlphaMultiPassText25 = new javax.swing.JLabel();
        AlphaMultiPassTick8 = new javax.swing.JCheckBox();
        AlphaMultiPassText26 = new javax.swing.JLabel();
        AlphaMultiPassTick9 = new javax.swing.JCheckBox();
        AlphaMultiPassText27 = new javax.swing.JLabel();
        AlphaMultiPassTick10 = new javax.swing.JCheckBox();
        AlphaMultiPassText28 = new javax.swing.JLabel();
        AlphaMultiPassTick11 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn1.setText("Save");
        SaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        AlphaMultiPassText18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText18.setText("DisableXA Decoding");
        MainPanel.add(AlphaMultiPassText18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 200, 20));
        MainPanel.add(AlphaMultiPassTick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, -1));

        AlphaMultiPassText19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText19.setText("Sio Iqr Always Enabled");
        MainPanel.add(AlphaMultiPassText19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, 20));
        MainPanel.add(AlphaMultiPassTick2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, -1));

        AlphaMultiPassText20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText20.setText("Spu Iqr Always Enabled");
        MainPanel.add(AlphaMultiPassText20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 20));
        MainPanel.add(AlphaMultiPassTick3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, -1));

        AlphaMultiPassText21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText21.setText("Black & White Movies");
        MainPanel.add(AlphaMultiPassText21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 200, 20));
        MainPanel.add(AlphaMultiPassTick4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 240, -1));

        AlphaMultiPassText22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText22.setText("Parasite Eve 2, Vandal Hearts 1/2 Fix");
        MainPanel.add(AlphaMultiPassText22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 200, 20));
        MainPanel.add(AlphaMultiPassTick5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, -1));

        AlphaMultiPassText23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText23.setText("InuYasha Sengoku Battle Fix");
        MainPanel.add(AlphaMultiPassText23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 20));
        MainPanel.add(AlphaMultiPassTick6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        AlphaMultiPassText24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText24.setText("Slow Boot");
        MainPanel.add(AlphaMultiPassText24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 200, 20));
        MainPanel.add(AlphaMultiPassTick7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 240, -1));

        AlphaMultiPassText25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText25.setText("Disable CD Audio");
        MainPanel.add(AlphaMultiPassText25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 200, 20));
        MainPanel.add(AlphaMultiPassTick8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 240, -1));

        AlphaMultiPassText26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText26.setText("Enable Console Output");
        MainPanel.add(AlphaMultiPassText26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 200, 20));
        MainPanel.add(AlphaMultiPassTick9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 240, -1));

        AlphaMultiPassText27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText27.setText("Enable Interpreter CPU");
        MainPanel.add(AlphaMultiPassText27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 200, 20));
        MainPanel.add(AlphaMultiPassTick10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 240, -1));

        AlphaMultiPassText28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText28.setForeground(new java.awt.Color(204, 204, 204));
        AlphaMultiPassText28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText28.setText("Enable Debugger");
        MainPanel.add(AlphaMultiPassText28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 200, 20));

        AlphaMultiPassTick11.setEnabled(false);
        MainPanel.add(AlphaMultiPassTick11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlphaMultiPassText18;
    private javax.swing.JLabel AlphaMultiPassText19;
    private javax.swing.JLabel AlphaMultiPassText20;
    private javax.swing.JLabel AlphaMultiPassText21;
    private javax.swing.JLabel AlphaMultiPassText22;
    private javax.swing.JLabel AlphaMultiPassText23;
    private javax.swing.JLabel AlphaMultiPassText24;
    private javax.swing.JLabel AlphaMultiPassText25;
    private javax.swing.JLabel AlphaMultiPassText26;
    private javax.swing.JLabel AlphaMultiPassText27;
    private javax.swing.JLabel AlphaMultiPassText28;
    private javax.swing.JCheckBox AlphaMultiPassTick1;
    private javax.swing.JCheckBox AlphaMultiPassTick10;
    private javax.swing.JCheckBox AlphaMultiPassTick11;
    private javax.swing.JCheckBox AlphaMultiPassTick2;
    private javax.swing.JCheckBox AlphaMultiPassTick3;
    private javax.swing.JCheckBox AlphaMultiPassTick4;
    private javax.swing.JCheckBox AlphaMultiPassTick5;
    private javax.swing.JCheckBox AlphaMultiPassTick6;
    private javax.swing.JCheckBox AlphaMultiPassTick7;
    private javax.swing.JCheckBox AlphaMultiPassTick8;
    private javax.swing.JCheckBox AlphaMultiPassTick9;
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SaveBtn1;
    // End of variables declaration//GEN-END:variables
}
