/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.Sounds;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class SoundSettings extends javax.swing.JFrame {

    private SoundSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public SoundSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        InterpolationText = new javax.swing.JLabel();
        VolumeText = new javax.swing.JLabel();
        ModeText = new javax.swing.JLabel();
        ReverbText = new javax.swing.JLabel();
        InterpolationBox = new javax.swing.JComboBox<>();
        VolumeBox = new javax.swing.JComboBox<>();
        ModeBox = new javax.swing.JComboBox<>();
        ReverbBox = new javax.swing.JComboBox<>();
        SaveBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        AdvancedSettingsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InterpolationText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InterpolationText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InterpolationText.setText("Interpolation");
        MainPanel.add(InterpolationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 40));

        VolumeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VolumeText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        VolumeText.setText("Volume");
        MainPanel.add(VolumeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 70, 40));

        ModeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ModeText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ModeText.setText("Mode");
        MainPanel.add(ModeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 40));

        ReverbText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ReverbText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ReverbText.setText("Reverb");
        MainPanel.add(ReverbText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 40));

        InterpolationBox.setBackground(new java.awt.Color(204, 204, 204));
        InterpolationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Simple", "Gaussian", "Cubic" }));
        InterpolationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterpolationBoxActionPerformed(evt);
            }
        });
        MainPanel.add(InterpolationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 240, -1));

        VolumeBox.setBackground(new java.awt.Color(204, 204, 204));
        VolumeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loudest (default)", "Loud", "Medium", "Low", "None" }));
        VolumeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBoxActionPerformed(evt);
            }
        });
        MainPanel.add(VolumeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 240, -1));

        ModeBox.setBackground(new java.awt.Color(204, 204, 204));
        ModeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fast", "High Compatibility", "SPU Async" }));
        ModeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeBoxActionPerformed(evt);
            }
        });
        MainPanel.add(ModeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 240, -1));

        ReverbBox.setBackground(new java.awt.Color(204, 204, 204));
        ReverbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PSX (Default)", "Simple", "None" }));
        ReverbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReverbBoxActionPerformed(evt);
            }
        });
        MainPanel.add(ReverbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 240, -1));

        SaveBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn1.setText("Save");
        SaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        AdvancedSettingsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdvancedSettingsBtn.setText("Advanced Settings");
        AdvancedSettingsBtn.setToolTipText("Settings for advanced users");
        AdvancedSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancedSettingsBtnActionPerformed(evt);
            }
        });
        MainPanel.add(AdvancedSettingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hci_assignment/images/Settings_bg1Small.png"))); // NOI18N
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InterpolationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterpolationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InterpolationBoxActionPerformed
    
    //First box
    private void VolumeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeBoxActionPerformed

    private void ModeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeBoxActionPerformed

    private void ReverbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReverbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReverbBoxActionPerformed

    private void AdvancedSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancedSettingsBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run() 
            {
                AdvancedSoundSettings ass = new AdvancedSoundSettings(thisClass);
                thisClass.setVisible(false);
                ass.setVisible(true);
            }
        });
    }//GEN-LAST:event_AdvancedSettingsBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdvancedSettingsBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox<String> InterpolationBox;
    private javax.swing.JLabel InterpolationText;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox<String> ModeBox;
    private javax.swing.JLabel ModeText;
    private javax.swing.JComboBox<String> ReverbBox;
    private javax.swing.JLabel ReverbText;
    private javax.swing.JButton SaveBtn1;
    private javax.swing.JComboBox<String> VolumeBox;
    private javax.swing.JLabel VolumeText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
