/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci_assignment.CDROM;

import hci_assignment.BG_COLOR.BACKGROUND_COLOR;
import javax.swing.JFrame;

/**
 *
 * @author Janek
 */
public class CDROMSettings extends javax.swing.JFrame {

    private CDROMSettings thisClass;
    private javax.swing.JFrame previousWindow;
    //private javax.swing.JLabel BG_image;
    /**
     * Creates new form SoundSettings
     */
    public CDROMSettings(javax.swing.JFrame previousWindow) {
        initComponents();
        thisClass = this;
        this.previousWindow = previousWindow;
        MainPanel.setBackground(BACKGROUND_COLOR.color);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SaveBtn1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        AlphaMultiPassText23 = new javax.swing.JLabel();
        AlphaMultiPassTick6 = new javax.swing.JCheckBox();
        GraphicsText = new javax.swing.JLabel();
        GraphicsBox = new javax.swing.JComboBox<>();
        GraphicsBox1 = new javax.swing.JComboBox<>();
        GraphicsText1 = new javax.swing.JLabel();
        GraphicsBox2 = new javax.swing.JComboBox<>();
        GraphicsText2 = new javax.swing.JLabel();
        GraphicsText3 = new javax.swing.JLabel();
        GraphicsBox3 = new javax.swing.JComboBox<>();
        GraphicsText4 = new javax.swing.JLabel();
        GraphicsText5 = new javax.swing.JLabel();
        GraphicsBox4 = new javax.swing.JComboBox<>();
        GraphicsText6 = new javax.swing.JLabel();
        GraphicsBox5 = new javax.swing.JComboBox<>();
        GraphicsText7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        GraphicsText8 = new javax.swing.JLabel();
        GraphicsText9 = new javax.swing.JLabel();
        GraphicsBox6 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn1.setText("Save");
        SaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn1ActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        MainPanel.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, -1, -1));

        AlphaMultiPassText23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlphaMultiPassText23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AlphaMultiPassText23.setText("Track ISO9660 File System");
        MainPanel.add(AlphaMultiPassText23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 200, 20));

        AlphaMultiPassTick6.setSelected(true);
        MainPanel.add(AlphaMultiPassTick6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 240, -1));

        GraphicsText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GraphicsText.setText("Performance");
        MainPanel.add(GraphicsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 100, 20));

        GraphicsBox.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autodetect" }));
        GraphicsBox.setToolTipText("");
        GraphicsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBoxActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 260, -1));

        GraphicsBox1.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autodetect", "IOCTL/SCSI", "ASPI", "IOCTL/RAW" }));
        GraphicsBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBox1ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 260, -1));

        GraphicsText1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText1.setText("Interface Type");
        MainPanel.add(GraphicsText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 20));

        GraphicsBox2.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autodetect", "SCSI_BE (READ_CD)", "SCSI_28 (READ_10)", "SCSI_D8 (CUSTOM)", "SCSI_D4 (CUSTOM)" }));
        GraphicsBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBox2ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 260, -1));

        GraphicsText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText2.setText("Read Mode");
        MainPanel.add(GraphicsText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, 20));

        GraphicsText3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText3.setText("Read Mode");
        MainPanel.add(GraphicsText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, 20));

        GraphicsBox3.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autodetect", "SCSI_BE+96", "SCSI_BE+16", "SCSI_D8+96", "SCSI_D8+16", "SCSI_28+96", "SCSI_28+16", "SCSI_42/RAW", "Disabled" }));
        GraphicsBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBox3ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 260, -1));

        GraphicsText4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText4.setText("Subchannel");
        MainPanel.add(GraphicsText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, 20));

        GraphicsText5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText5.setText("CDROM Speed");
        MainPanel.add(GraphicsText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 100, 20));

        GraphicsBox4.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "2X", "4X", "6X", "8X", "12X", "16X", "MAX"  }));
        GraphicsBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBox4ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 260, -1));

        GraphicsText6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText6.setText("CDROM Spindown");
        MainPanel.add(GraphicsText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 120, 20));

        GraphicsBox5.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "32 sec", "1 min", "2 min", "4 min", "8 min", "16 min"  }));
        GraphicsBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBox5ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 260, -1));

        GraphicsText7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText7.setText("Drive Selection");
        MainPanel.add(GraphicsText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        MainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 10, 280));

        GraphicsText8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GraphicsText8.setText("Drive Properties");
        MainPanel.add(GraphicsText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 20));

        GraphicsText9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GraphicsText9.setText("Caching level");
        MainPanel.add(GraphicsText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 100, 20));

        GraphicsBox6.setBackground(new java.awt.Color(204, 204, 204));
        GraphicsBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0. Disabled", "1. Read one sector a time", "2. Prefetch multiple sectors", "3. Prefetch with async reads (recommended)" }));
        GraphicsBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsBox6ActionPerformed(evt);
            }
        });
        MainPanel.add(GraphicsBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            previousWindow.setVisible(true);
            thisClass.dispose();
        });
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtn1ActionPerformed

    private void GraphicsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBoxActionPerformed

    private void GraphicsBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBox1ActionPerformed

    private void GraphicsBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBox2ActionPerformed

    private void GraphicsBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBox3ActionPerformed

    private void GraphicsBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBox4ActionPerformed

    private void GraphicsBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBox5ActionPerformed

    private void GraphicsBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsBox6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlphaMultiPassText23;
    private javax.swing.JCheckBox AlphaMultiPassTick6;
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox<String> GraphicsBox;
    private javax.swing.JComboBox<String> GraphicsBox1;
    private javax.swing.JComboBox<String> GraphicsBox2;
    private javax.swing.JComboBox<String> GraphicsBox3;
    private javax.swing.JComboBox<String> GraphicsBox4;
    private javax.swing.JComboBox<String> GraphicsBox5;
    private javax.swing.JComboBox<String> GraphicsBox6;
    private javax.swing.JLabel GraphicsText;
    private javax.swing.JLabel GraphicsText1;
    private javax.swing.JLabel GraphicsText2;
    private javax.swing.JLabel GraphicsText3;
    private javax.swing.JLabel GraphicsText4;
    private javax.swing.JLabel GraphicsText5;
    private javax.swing.JLabel GraphicsText6;
    private javax.swing.JLabel GraphicsText7;
    private javax.swing.JLabel GraphicsText8;
    private javax.swing.JLabel GraphicsText9;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SaveBtn1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
